"""
The scope works similar to the ASG but in reverse: Two channels are
available. A table of :math:`2^{14}` datapoints for each channel is
filled with the time series of incoming data. Downloading a full trace
takes about 10 ms over standard ethernet. The rate at which the memory
is filled is the sampling rate (125 MHz) divided by the value of
'decimation'. The property 'average' decides whether each datapoint is a
single sample or the average of all samples over the decimation
interval.

.. code:: python

    s = r.scope # shortcut
    print("Available decimation factors:", s.decimations)
    print("Trigger sources:", s.trigger_sources)
    print("Available inputs: ", s.inputs)

Let's have a look at a signal generated by asg1. Later we will use
convenience functions to reduce the amount of code necessary to set up
the scope:

.. code:: python

    asg = r.asg1
    s = r.scope

    # turn off asg so the scope has a chance to measure its "off-state" as well
    asg.output_direct = "off"

    # setup scope
    s.input1 = 'asg1'

    # pass asg signal through pid0 with a simple integrator - just for fun (detailed explanations for pid will follow)
    r.pid0.input = 'asg1'
    r.pid0.ival = 0 # reset the integrator to zero
    r.pid0.i = 1000 # unity gain frequency of 1000 hz
    r.pid0.p = 1.0 # proportional gain of 1.0
    r.pid0.inputfilter = [0,0,0,0] # leave input filter disabled for now

    # show pid output on channel2
    s.input2 = 'pid0'

    # trig at zero volt crossing
    s.threshold_ch1 = 0

    # positive/negative slope is detected by waiting for input to
    # sweep through hysteresis around the trigger threshold in
    # the right direction
    s.hysteresis_ch1 = 0.01

    # trigger on the input signal positive slope
    s.trigger_source = 'ch1_positive_edge'

    # take data symetrically around the trigger event
    s.trigger_delay = 0

    # set decimation factor to 64 -> full scope trace is 8ns * 2^14 * decimation = 8.3 ms long
    s.decimation = 64

    # launch a single (asynchronous) curve acquisition, the asynchronous
    # acquisition means that the function returns immediately, eventhough the
    # data-acquisition is still going on.
    res = s.curve_async()

    print("Before turning on asg:")
    print("Curve ready:", s.curve_ready()) # trigger should still be armed

    # turn on asg and leave enough time for the scope to record the data
    asg.setup(frequency=1e3, amplitude=0.3, start_phase=90, waveform='halframp', trigger_source='immediately')
    sleep(0.010)

    # check that the trigger has been disarmed
    print("After turning on asg:")
    print("Curve ready:", s.curve_ready())
    print("Trigger event age [ms]:",8e-9*((
    s.current_timestamp&0xFFFFFFFFFFFFFFFF) - s.trigger_timestamp)*1000)

    # The function curve_async returns a *future* (or promise) of the curve. To
    # access the actual curve, use result()
    ch1, ch2 = res.result()

    # plot the data
    %matplotlib inline
    plt.plot(s.times*1e3, ch1, s.times*1e3, ch2)
    plt.xlabel("Time [ms]")
    plt.ylabel("Voltage")

What do we see? The blue trace for channel 1 shows just the output
signal of the asg. The time=0 corresponds to the trigger event. One can
see that the trigger was not activated by the constant signal of 0 at
the beginning, since it did not cross the hysteresis interval. One can
also see a 'bug': After setting up the asg, it outputs the first value
of its data table until its waveform output is triggered. For the
halframp signal, as it is implemented in pyrpl, this is the maximally
negative value. However, we passed the argument start_phase=90 to the
asg.setup function, which shifts the first point by a quarter period.
Can you guess what happens when we set start_phase=180? You should try
it out!

In green, we see the same signal, filtered through the pid module. The
nonzero proportional gain leads to instant jumps along with the asg
signal. The integrator is responsible for the constant decrease rate at
the beginning, and the low-pass that smoothens the asg waveform a
little. One can also foresee that, if we are not paying attention, too
large an integrator gain will quickly saturate the outputs.

.. code:: python

    # useful functions for scope diagnostics
    print("Curve ready:", s.curve_ready())
    print("Trigger source:",s.trigger_source)
    print("Trigger threshold [V]:",s.threshold_ch1)
    print("Averaging:",s.average)
    print("Trigger delay [s]:",s.trigger_delay)
    print("Trace duration [s]: ",s.duration)
    print("Trigger hysteresis [V]", s.hysteresis_ch1)
    print("Current scope time [cycles]:",hex(s.current_timestamp))
    print("Trigger time [cycles]:",hex(s.trigger_timestamp))
    print("Current voltage on channel 1 [V]:", r.scope.voltage_in1)
    print("First point in data buffer 1 [V]:", s.ch1_firstpoint)
"""

import time
import contextlib
from .dsp import all_inputs, dsp_addr_base, InputSelectRegister
from .dma_client import DmaUdpClient
from ..acquisition_module import AcquisitionModule
from ..async_utils import wait, ensure_future, sleep_async
from ..pyrpl_utils import sorted_dict
from ..attributes import *
from ..modules import HardwareModule
from ..pyrpl_utils import time
from ..widgets.module_widgets import ScopeWidget

logger = logging.getLogger(name=__name__)

data_length = 2**14

class StatusBitsProperty(StringProperty):
    names = {
        0:'busy',
        2:'adc_dly_do',
        3:'adc_we_keep',
        4:'fft_parallel',
        5:'fft_enable',
        6:'fft_trig_sync',
        7:'fft_a_done',
        8:'fft_b_done',
        9:'fft_a_peak_ready',
        10:'fft_b_peak_ready',
        16:'fft_a_tlast_unexp',
        17:'fft_a_tlast_missing',
        18:'fft_a_frame_start',
        19:'fft_a_status_halt',
        20:'fft_a_in_halt',
        21:'fft_a_out_halt',
        24:'fft_b_tlast_unexp',
        25:'fft_b_tlast_missing',
        26:'fft_b_frame_start',
        27:'fft_b_status_halt',
        28:'fft_b_in_halt',
        29:'fft_b_out_halt',
    }
    def set_value(self, obj):
        pass

    def get_value(self, obj):
        bits = []
        for i,j in enumerate(reversed(bin(obj._status))):
            if j == '1':
                bits.append(f'{i}: {self.names.get(i, "?")}')
        return '\n'.join(bits)

# ==========================================
# The following properties are all linked:
#  - decimation
#  - duration
#  - sampling_time
# decimation is the "master": changing it updates
# the 2 others.
# ==========================================
class DecimationRegister(SelectRegister):
    """
    Careful: changing decimation changes duration and sampling_time as well
    """
    def set_value(self, obj, value):
        SelectRegister.set_value(self, obj, value)
        obj.__class__.duration.value_updated(obj, obj.duration)
        obj.__class__.sampling_time.value_updated(obj, obj.sampling_time)


class DurationProperty(SelectProperty):
    def get_value(self, obj):
        return obj.sampling_time * float(obj.data_length)

    def validate_and_normalize(self, obj, value):
        # gets next-higher value
        value = float(value)
        options = self.options(obj).keys()
        try:
            return min([opt for opt in options if opt >= value],
                   key=lambda x: abs(x - value))
        except ValueError:
            obj._logger.info("Selected duration is longer than "
                             "physically possible with the employed hardware. "
                             "Picking longest-possible value %s. ",
                             max(options))
            return max(options)

    def set_value(self, obj, value):
        """sets returns the duration of a full scope sequence the rounding
        makes sure that the actual value is longer or equal to the set value"""
        obj.sampling_time = float(value) / obj.data_length


class SamplingTimeProperty(SelectProperty):
    def get_value(self, obj):
        return 8e-9 * float(obj.decimation)

    def validate_and_normalize(self, obj, value):
        # gets next-lower value
        value = float(value)
        options = self.options(obj).keys()
        try:
            return min([opt for opt in options if opt <= value],
                   key=lambda x: abs(x - value))
        except ValueError:
            obj._logger.info("Selected sampling time is shorter than "
                             "physically possible with the employed hardware. "
                             "Picking shortest-possible value %s. ",
                             min(options))
            return min(options)

    def set_value(self, instance, value):
        """sets or returns the time separation between two subsequent
        points of a scope trace the rounding makes sure that the actual
        value is shorter or equal to the set value"""
        instance.decimation = float(value) / 8e-9


class DmaMaxIntervalProperty(FloatProperty):
    """FloatProperty that also pushes the new value into a running DMA UDP client,
    so the publish cadence applies live (no acquisition restart needed).

    Negative values are a MULTIPLIER of the scan's theoretical frame period
    (-2 = a fallback publish every two raster periods, for a stalled frame
    counter). The scope cannot derive that period itself, so a negative value
    is only STORED here — the lidar layer (pointcloud._sync_dma_parse_rate)
    converts it to seconds from the measured scan rate and pushes the result
    straight to the client."""
    def set_value(self, obj, val):
        super(DmaMaxIntervalProperty, self).set_value(obj, val)
        client = getattr(obj, '_dma_udp_client', None)
        if client is not None and float(val) >= 0:
            client.configure(max_interval=float(val))
        return val


class DmaUnicastProperty(BoolProperty):
    """BoolProperty selecting how the host receives the DMA point cloud:
    True  = unicast (monitor_server sends straight to this host; default),
    False = join the multicast group. Unicast avoids multicast interface-
    selection problems on multi-homed hosts (e.g. Windows with several virtual
    NICs). Changing it updates the UDP client and, if a receiver is already
    running, stops it so the next acquisition restarts in the new mode (the
    (re)start is gated in Scope._start_trace_acquisition)."""
    def set_value(self, obj, val):
        super(DmaUnicastProperty, self).set_value(obj, val)
        client = getattr(obj, '_dma_udp_client', None)
        if client is not None and client._unicast != bool(val):
            client._unicast = bool(val)
            client.stop()  # restarted in the new mode on the next acquisition
        return val


class _AzModulusRegister(IntRegister):
    """enc_az_modulus with a bound from the bitstream: the DMA cell's tick field
    is TKW = HSZ - MSW bits (descriptor 0x1A4), and the encoder latches ticks
    >= T as T itself, so T must fit that field or the overflow bucket aliases
    into the frame. Clamps with a warning instead of writing an unusable T."""
    def validate_and_normalize(self, obj, value):
        value = super(_AzModulusRegister, self).validate_and_normalize(obj, value)
        try:
            tkw = int(obj.dma_az_tkw) if obj._dma_azimuth_cap else 0
        except Exception:
            tkw = 0
        if tkw and value > (1 << tkw) - 1:
            obj._logger.warning(
                "enc_az_modulus %d exceeds the azimuth cell tick field "
                "(%d bits); clamping to %d", value, tkw, (1 << tkw) - 1)
            value = (1 << tkw) - 1
        return value


class Scope(HardwareModule, AcquisitionModule):
    MIN_DELAY_CONTINUOUS_ROLLING_MS = 20
    addr_base = 0x40200000
    name = 'scope'
    _widget_class = ScopeWidget
    # run = ModuleProperty(ScopeAcquisitionManager)
    _gui_attributes = ["input1",
                       "input2",
                       "duration",
                       "average",
                       "trigger_source",
                       "trigger_delay",
                       "threshold",
                       #"threshold_ch1",
                       #"threshold_ch2",
                       "hysteresis",
                       "ch1_active",
                       "ch2_active",
                       "ch_math_active",
                       "math_formula",
                       "xy_mode"]
    # running_state last for proper acquisition setup
    _setup_attributes = _gui_attributes + ["rolling_mode", "fft_enable", 'fft_parallel',
                                           'nfft', 'dma_max_interval', 'dma_unicast']
    # changing these resets the acquisition and autoscale (calls setup())

    data_length = data_length  # to use it in a list comprehension

    rolling_mode = BoolProperty(default=True,
                                doc="In rolling mode, the curve is "
                                    "continuously acquired and "
                                    "translated from the right to the "
                                    "left of the screen while new "
                                    "data arrive.",
                                call_setup=True)

    @property
    def inputs(self):
        return list(all_inputs(self).keys())

    # the scope inputs and asg outputs have the same dsp id
    input1 = InputSelectRegister(- addr_base + dsp_addr_base('asg0') + 0x0,
                                 options=all_inputs,
                                 default='in1',
                                 ignore_errors=True,
                                 doc="selects the input signal of the module")

    input2 = InputSelectRegister(- addr_base + dsp_addr_base('asg1') + 0x0,
                                 options=all_inputs,
                                 default='in2',
                                 ignore_errors=True,
                                 doc="selects the input signal of the module")

    _reset_writestate_machine = BoolRegister(0x0, 1,
                                             doc="Set to True to reset "
                                                 "writestate machine. "
                                                 "Automatically goes back "
                                                 "to false.")

    fft_dclk = BoolRegister(0x0, 11, doc="Double clock speed for fft")

    _reset_peak_ready_a = BoolRegister(0x0, 9)
    _reset_peak_ready_b = BoolRegister(0x0, 10)

    _trigger_armed = BoolRegister(0x0, 0, doc="Set to True to arm trigger")

    _trigger_sources = sorted_dict({"off": 0,
                                    "immediately": 1,
                                    "ch1_positive_edge": 2,
                                    "ch1_negative_edge": 3,
                                    "ch2_positive_edge": 4,
                                    "ch2_negative_edge": 5,
                                    "ext_positive_edge": 6,  # DIO0_P pin
                                    "ext_negative_edge": 7,  # DIO0_P pin
                                    "asg0": 8,
                                    "asg1": 9,
                                    "asg2": 11,
                                    "asg3": 12,
                                    "dsp": 10, #dsp trig module trigger
                                    "enc_tick": 13}, # Scanner360 gated encoder
                                                     # tick (no debounce)
                                    sort_by_values=True)

    trigger_sources = _trigger_sources.keys()  # help for the user

    _trigger_source_register = SelectRegister(0x4, doc="Trigger source",
                                              options=_trigger_sources)

    trigger_source = ExtTriggerSelectProperty(default='immediately',
                                    options=_trigger_sources.keys(),
                                    doc="Trigger source for the scope. Use "
                                        "'immediately' if no "
                                        "synchronisation is required. "
                                        "Trigger_source will be ignored in "
                                        "rolling_mode.",
                                    call_setup=True)

    _trigger_debounce = IntRegister(0x90, doc="Trigger debounce time [cycles]")

    trigger_debounce = FloatRegister(0x90, bits=20, norm=125e6,
                                     doc="Trigger debounce time [s]")

    # same theshold and hysteresis for both channels
    threshold = FloatRegister(0x8, bits=14, norm=2 ** 13,
                                  doc="trigger threshold [volts]")
    hysteresis = FloatRegister(0x20, bits=14, norm=2 ** 13,
                                    doc="hysteresis for trigger [volts]")

    @property
    def threshold_ch1(self):
        self._logger.warning('The scope attribute "threshold_chx" is deprecated. '
                             'Please use "threshold" instead!')
        return self.threshold
    @threshold_ch1.setter
    def threshold_ch1(self, v):
        self._logger.warning('The scope attribute "threshold_chx" is deprecated. '
                             'Please use "threshold" instead!')
        self.threshold = v
    @property
    def threshold_ch2(self):
        self._logger.warning('The scope attribute "threshold_chx" is deprecated. '
                             'Please use "threshold" instead!')
        return self.threshold
    @threshold_ch2.setter
    def threshold_ch2(self, v):
        self._logger.warning('The scope attribute "threshold_chx" is deprecated. '
                             'Please use "threshold" instead!')
        self.threshold = v
    @property
    def hysteresis_ch1(self):
        self._logger.warning('The scope attribute "hysteresis_chx" is deprecated. '
                             'Please use "hysteresis" instead!')
        return self.hysteresis
    @hysteresis_ch1.setter
    def hysteresis_ch1(self, v):
        self._logger.warning('The scope attribute "hysteresis_chx" is deprecated. '
                             'Please use "hysteresis" instead!')
        self.hysteresis = v
    @property
    def hysteresis_ch2(self):
        self._logger.warning('The scope attribute "hysteresis_chx" is deprecated. '
                             'Please use "hysteresis" instead!')
        return self.hysteresis
    @hysteresis_ch2.setter
    def hysteresis_ch2(self, v):
        self._logger.warning('The scope attribute "hysteresis_chx" is deprecated. '
                             'Please use "hysteresis" instead!')
        self.hysteresis = v
    #threshold_ch1 = FloatRegister(0x8, bits=14, norm=2 ** 13,
    #                              doc="ch1 trigger threshold [volts]")
    #threshold_ch2 = FloatRegister(0xC, bits=14, norm=2 ** 13,
    #                              doc="ch1 trigger threshold [volts]")
    #hysteresis_ch1 = FloatRegister(0x20, bits=14, norm=2 ** 13,
    #                               doc="hysteresis for ch1 trigger [volts]")
    #hysteresis_ch2 = FloatRegister(0x24, bits=14, norm=2 ** 13,
    #                               doc="hysteresis for ch2 trigger [volts]")

    _trigger_delay_register = IntRegister(0x10,
                                 doc="number of decimated data after trigger "
                                     "written into memory [samples]")

    trigger_delay = FloatProperty(min=-10, # TriggerDelayAttribute
                                  max=8e-9 * 2 ** 30,
                                  doc="delay between trigger and "
                                      "acquisition start.\n"
                                      "negative values down to "
                                      "-duration are allowed for "
                                      "pretrigger. "
                                      "In trigger_source='immediately', "
                                      "trigger_delay is ignored.",
                                  call_setup=True)

    _trigger_delay_running = BoolRegister(0x0, 2,
                                          doc="trigger delay running ("
                                              "register adc_dly_do)")

    _adc_we_keep = BoolRegister(0x0, 3,
                                doc="Scope resets trigger automatically ("
                                    "adc_we_keep)")

    fft_enable = BoolRegister(0x0, 5, doc="Enable fft")

    dma_nch = IntRegister(0x98,
                          doc="Number of FFT channels streamed over the point-"
                              "cloud DMA: 0 = DMA off, 1 = ch0 only, 2 = ch0+ch1. "
                              "Clamped in the FPGA to the channels present.")

    dma_max_interval = DmaMaxIntervalProperty(default=0.0, min=-100.0, max=100.0,
                                     doc="Max seconds between published point-cloud "
                                         "frames when points keep arriving but the 2D "
                                         "scan does not turn over (e.g. a paused "
                                         "scanner). 0 = always expose the live buffer "
                                         "on any update; >0 = frame-coherent snapshot "
                                         "refreshed at least this often; <0 = "
                                         "multiplier of the scan's theoretical frame "
                                         "period (-2 = fallback publish every two "
                                         "raster periods, for a stalled frame counter; "
                                         "derived and pushed by the lidar layer). "
                                         "Applies live.")

    dma_unicast = DmaUnicastProperty(default=True,
                                     doc="Receive the DMA point cloud as unicast "
                                         "(monitor_server sends it straight to this "
                                         "host) instead of joining the multicast "
                                         "group. Avoids multicast interface-selection "
                                         "problems on multi-homed hosts (e.g. Windows "
                                         "with several virtual NICs). Applies on the "
                                         "next acquisition.")

    fft_parallel = BoolRegister(0x0, 4, doc="Running dual fft in parallel for up and down")

    fft_trigger_sync = BoolRegister(0x0, 6, doc='Sync fft trigger to scope')

    _status = IntRegister(0x00)

    status_bits = StatusBitsProperty()

    fft_point_cnt = IntRegister(0x30, doc="FFT point counter (per detected point)")
    fft_scan_point_cnt = IntRegister(0x74, doc="FFT scan-point counter (per scan-position change)")

    fft_peak_start = IntRegister(0x38, doc="FFT peak detection start index")

    fft_peak_threshold = IntRegister(0x3C, doc="FFT peak detection threshold")

    fft_peak_minimum = IntRegister(0x40, doc="FFT peak detection lower bound")

    fft_peak_idx_a = IntRegister(0x44, doc="FFT channel A peak indices")

    fft_peak_idx_b = IntRegister(0x7C, doc="FFT channel B peak indices")

    fft_peak_up_a = IntRegister(0x48, doc="FFT channel A up peak value")

    fft_peak_down_a = IntRegister(0x4C, doc="FFT channel A down peak value")

    fft_peak_up_b = IntRegister(0x80, doc="FFT channel B up peak value")

    fft_peak_down_b = IntRegister(0x84, doc="FFT channel B down peak value")

    fft_cfar_guard = IntRegister(0x50, doc="CA-CFAR: guard cells each side of the "
                                 "peak (excluded from the local noise estimate)")

    fft_cfar_train = IntRegister(0x54, doc="CA-CFAR: training/reference cells each "
                                 "side used to estimate the local noise floor. "
                                 "Must not exceed the image's CFAR_TRAIN_MAX "
                                 "(63 on n11 builds, 64 otherwise) — beyond it "
                                 "the window loop and count fields overflow")

    fft_cfar_onesided = BoolRegister(0xA4, 0, doc="CA-CFAR: near-cutoff one-sided "
                                     "fallback — a candidate inside the edge-guard "
                                     "dead zone (left reference band out of band) "
                                     "is tested against the in-band cells only, "
                                     "gated by guard-span clearance (any louder "
                                     "below-cutoff cell within the guard span "
                                     "rejects it as a skirt shoulder). Reset 1; "
                                     "0 = classic hard two-sided guard")

    fft_cfar_so = BoolRegister(0xA8, 0, doc="CA-CFAR -> SO-CFAR (Smallest-Of): "
                               "judge the candidate against the QUIETER of the two "
                               "reference bands alone instead of pooling both, so an "
                               "interferer in ONE band cannot inflate the reference "
                               "variance and mask a genuine peak. Biases the noise "
                               "estimate low, so raise fft_peak_threshold with it "
                               "(~3.6x more false alarms at k^2=30 otherwise). "
                               "Reset 0 = classic CA")

    # Baseline ramp: a magnitude is scaled by g(bin) = 2^-d(bin), where
    #     d(bin) = max(0, ramp_d0 - ramp_step * (bin - fft_peak_start))
    # in Q(6).(20) log2-of-magnitude units. The clamp at zero IS the hold-last,
    # so there is no ramp-end register. ramp_d0 = 0 disables the ramp exactly.
    # The correction applies to candidate SELECTION and to the CFAR window
    # statistics; the reported peak amplitude stays raw.
    FFT_RAMP_FRAC = 20              # fractional bits in both ramp registers

    fft_ramp_d0 = IntRegister(0xAC, doc="Baseline ramp: attenuation at the cutoff "
                              "bin (fft_peak_start), Q3.20 log2(magnitude) units. "
                              "0 = ramp disabled")

    fft_ramp_step = IntRegister(0xB0, doc="Baseline ramp: attenuation decrement per "
                                "bin, Q3.20 log2(magnitude) units. d clamps at 0, "
                                "which holds the correction flat past the ramp end")

    fft_wait1_cnt = IntRegister(0x58, doc="FFT first stage wait time counter")

    fft_wait2_cnt = IntRegister(0x5C, doc="FFT second stage wait time counter")

    fft_acq1_cnt = IntRegister(0x60, doc="FFT first stage acquisition time counter")

    fft_acq2_cnt = IntRegister(0x64, doc="FFT second stage acquisition time counter")

    fft_overflow_cnt = IntRegister(0x190, doc="FFT buffer overflow count")

    # Input-FIFO reset diagnostics, one per FFT engine. Packed 32-bit word:
    # [31:16] rst_drop   — ADC writes rejected while the per-frame FIFO reset was
    #                      still propagating (should stay 0 for any sane wait1)
    # [15:0]  zero_frame — frame halves fed with zero real data beats (the silent
    #                      all-zero-spectrum failure). Both wrap; take deltas.
    fft_diag_a = IntRegister(0x198, doc="FFT input-FIFO reset diagnostics, engine A")

    fft_diag_b = IntRegister(0x19C, doc="FFT input-FIFO reset diagnostics, engine B")

    fft_wp_last = IntRegister(0x68, doc="FFT last write size")

    # DMA point-cloud packet-format descriptor (read-only, self-describing).
    # Sub-fields of one packed FPGA register (0x170) so the host configures its
    # UDP unpacker from hardware instead of hardcoding. Data-word peak field
    # width is IDX = dma_fmt_fsz + dma_fmt_frac; bin = field / 2**dma_fmt_frac.
    dma_fmt_fsz = IntRegister(0x170, bits=8, bitmask=0x000000ff,
                              doc="DMA peak integer-bin width FSZ")
    dma_fmt_frac = IntRegister(0x170, bits=8, bitmask=0x0000ff00,
                               doc="DMA peak sub-bin fractional bits FRAC")
    dma_fmt_hsz = IntRegister(0x170, bits=8, bitmask=0x00ff0000,
                              doc="DMA header hist_index field width HSZ")
    dma_fmt_version = IntRegister(0x170, bits=8, bitmask=0xff000000,
                                  doc="DMA packet-layout version")
    dma_block_size = IntRegister(0x194, bits=16, bitmask=0x0000ffff,
                                 doc="DMA data words per packet (HIST_BLOCK_SIZE)")
    # Per-packet sequence width: how many LOW bits of the header frame_cnt field the
    # FPGA stamps as a monotonic per-packet counter. 0 on bitstreams without it (the
    # [27:20] spare bits read 0), so the host auto-disables seq drop-detection.
    dma_fmt_seq_bits = IntRegister(0x194, bits=8, bitmask=0x0ff00000,
                                   doc="DMA per-packet sequence width (header low bits)")
    # Runtime intensity support. _dma_intensity_cap feature-detects the 0x9C
    # enable register (older bitstreams read 0); _dma_intensity_en is the raw
    # enable bit. Use the dma_intensity property below, which also keeps the
    # UDP client's decode mode in sync.
    _dma_intensity_cap = BoolRegister(0x194, 28,
                                      doc="bitstream has the runtime DMA intensity enable")
    _dma_intensity_en = BoolRegister(0x9C, 0,
                                     doc="stream a value word (peak amplitudes) per point; "
                                         "takes effect at the next DMA packet boundary")

    # Scanner360 azimuth mode (see fpga/docs/Scanner360.md). Capability bit +
    # raw enable, wrapped by the dma_azimuth property below (which also keeps
    # the UDP client's decode mode in sync).
    _dma_azimuth_cap = BoolRegister(0x194, 29,
                                    doc="bitstream has the azimuth scan-cell / packet mode")
    _dma_azimuth_en = BoolRegister(0x9C, 1,
                                   doc="azimuth mode: scan cell = {tick, mems}, packet "
                                       "versions +4 (v7-v10); packet-boundary latched")
    # Azimuth packet-format descriptor (RO 0x1A4): cell = {tick[TKW], mems[MSW]},
    # data word carries a DTW-bit tick delta + the absolute mems field.
    dma_az_msw = IntRegister(0x1A4, bits=8, bitmask=0x000000ff,
                             doc="azimuth cell MEMS sub-field width MSW (stride 2^MSW)")
    dma_az_dtw = IntRegister(0x1A4, bits=8, bitmask=0x0000ff00,
                             doc="azimuth data-word tick-delta field width (bits)")
    dma_az_tkw = IntRegister(0x1A4, bits=8, bitmask=0x00ff0000,
                             doc="azimuth cell tick sub-field width (= HSZ - MSW)")

    # ---- Scanner360 encoder block (0x1A8-0x1BC) ----
    enc_enable = BoolRegister(0x1A8, 0,
                              doc="enable the encoder tick/turn front-end")
    enc_gate_asg = BoolRegister(0x1A8, 1,
                                doc="mask ticks while asg3 (chirp) is playing — a "
                                    "re-trigger would APPEND a chirp period, not restart")
    enc_gate_fft = BoolRegister(0x1A8, 2,
                                doc="mask ticks while the FFT frame is in flight "
                                    "(incl. fft_trig_delay) — a passed tick is "
                                    "guaranteed to become a point")
    enc_turn_source = BoolRegister(0x1A8, 3,
                                   doc="False = DIO0_N per-turn pulse, True = synthetic "
                                       "turn when tick_in_turn reaches enc_az_modulus")
    enc_divider = IntRegister(0x1A8, bits=4, bitmask=0x000000f0,
                              doc="fire every (N+1)-th tick (this register holds N); "
                                  "phase reset at the turn pulse. Keep 2*(N+1) <= 15 "
                                  "so a single busy-masked tick still fits the dt field")
    enc_glitch_log2 = IntRegister(0x1A8, bits=4, bitmask=0x00000f00,
                                  doc="glitch filter: pin level must hold 2^n adc "
                                      "cycles before an edge is accepted (0 = off)")
    enc_mems_turn_kick = IntRegister(0x1A8, bits=4, bitmask=0x0000f000,
                                     doc="extra MEMS step pulses injected at each turn "
                                         "pulse (forces the rosette precession "
                                         "regardless of T mod L); 0 = natural")
    enc_az_modulus = _AzModulusRegister(0x1AC, bits=16,
                                        doc="ticks per turn T: synthetic-turn modulus "
                                            "(enc_turn_source=True) / bound on the "
                                            "latched azimuth (ticks >= T land in the "
                                            "overflow bucket T, dropped by the host); "
                                            "clamped to the cell tick field 2^TKW-1")
    enc_tick_in_turn = IntRegister(0x1B0, bits=16, bitmask=0x0000ffff,
                                   doc="live 0-based azimuth tick counter (RO)")
    enc_turn_cnt = IntRegister(0x1B0, bits=16, bitmask=0xffff0000,
                               doc="live turn counter (RO, wraps at 2^16)")
    enc_ticks_last_turn = IntRegister(0x1B4, bits=16,
                                      doc="ticks counted between the last two turn "
                                          "pulses (RO; should equal T)")
    enc_turn_period = IntRegister(0x1B8,
                                  doc="adc_clk cycles of the last full turn (RO) "
                                      "-> f_rev = 125e6 / enc_turn_period")
    enc_ticks_masked = IntRegister(0x1BC, bits=16, bitmask=0x0000ffff,
                                   doc="divider-eligible ticks masked by the busy "
                                       "gate (RO, wrapping)")
    enc_ticks_fired = IntRegister(0x1BC, bits=16, bitmask=0xffff0000,
                                  doc="ticks that fired the trigger chain (RO, wrapping)")

    fft_debug2 = IntRegister(0x174)
    fft_debug3 = IntRegister(0x178)

    fft_state = IntRegister(0x6C, doc="FFT internal state")

    fft_we_cnt = IntRegister(0x70, doc="FFT write count")

    fft_peak_state = IntRegister(0x78, doc="FFT peak detection internal state")

    fft_hist_size = IntRegister(0x24, doc="FFT history buffer size")

    scan_pos = IntRegister(0x188, doc='scanning position')

    start_sig_delay = IntRegister(0x18C, doc='start signal delay, for triggering asg')

    fft_trig_delay = IntRegister(0x1A0,
                                 doc='Delay, in decimated samples, from the '
                                     'trigger to the start of the hardware fft '
                                     'acquisition window sequence. Compensates '
                                     'a laser driver lag (chirp answers the '
                                     'modulation trigger late). Set it to '
                                     'trigger_delay in samples and the fft '
                                     'trigger lands on the middle of the '
                                     'captured trace. MUST be less than one '
                                     'chirp period: a delay still in flight '
                                     'swallows the next chirp trigger.')

    nfft = IntRegister(0x88, doc="FFT point size configuration. Implies a transform length of 2^nfft",
                       min=3, max=16, call_setup=True)

    fft_length = IntRegister(0x8C, doc="FFT current point size")

    fft_data_width = IntRegister(0x34, doc='FFT data bit width')

    _adc_we_cnt = IntRegister(0x2C, doc="Number of samles that have passed "
                                        "since trigger was armed (adc_we_cnt)")

    current_timestamp = LongRegister(0x15C,
                                     bits=64,
                                     doc="An absolute counter "
                                         + "for the time [cycles]")

    trigger_timestamp = LongRegister(0x164,
                                     bits=64,
                                     doc="An absolute counter "
                                         + "for the trigger time [cycles]")

    _decimations = sorted_dict({2 ** n: 2 ** n for n in range(0, 17)},
                               sort_by_values=True)

    decimations = _decimations.keys()  # help for the user

    # decimation is the basic register, sampling_time and duration are slaves of it
    decimation = DecimationRegister(0x14, doc="decimation factor",
                                    default = 0x2000, # fpga default = 1s duration
                                    # customized to update duration and
                                    # sampling_time
                                    options=_decimations,
                                    call_setup=True)

    _decimation_register = IntRegister(0x14, doc="decimation register value", call_setup=True)

    sampling_times = [8e-9 * dec for dec in decimations]

    sampling_time = SamplingTimeProperty(options=sampling_times)

    # list comprehension workaround for python 3 compatibility
    # cf. http://stackoverflow.com/questions/13905741
    durations = [st * data_length for st in sampling_times]

    duration = DurationProperty(options=durations)

    _write_pointer_current = IntRegister(0x18,
                                         doc="current write pointer "
                                             "position [samples]")

    _write_pointer_trigger = IntRegister(0x1C,
                                         doc="write pointer when trigger "
                                             "arrived [samples]")

    average = BoolRegister(0x28, 0,
                           doc="Enables averaging during decimation if set "
                               "to True")

    # equalization filter not implemented here

    voltage_in1 = FloatRegister(0x154, bits=14, norm=2 ** 13,
                                doc="in1 current value [volts]")

    voltage_in2 = FloatRegister(0x158, bits=14, norm=2 ** 13,
                                doc="in2 current value [volts]")

    voltage_out1 = FloatRegister(0x164, bits=14, norm=2 ** 13,
                                 doc="out1 current value [volts]")

    voltage_out2 = FloatRegister(0x168, bits=14, norm=2 ** 13,
                                 doc="out2 current value [volts]")

    ch1_firstpoint = FloatRegister(0x10000, bits=14, norm=2 ** 13,
                                   doc="1 sample of ch1 data [volts]")

    ch2_firstpoint = FloatRegister(0x20000, bits=14, norm=2 ** 13,
                                   doc="1 sample of ch2 data [volts]")

    pretrig_ok = BoolRegister(0x16c, 0,
                              doc="True if enough data have been acquired "
                                  "to fill the pretrig buffer")

    ch1_active = BoolProperty(default=True,
                              doc="should ch1 be displayed in the gui?")

    ch2_active = BoolProperty(default=True,
                              doc="should ch2 be displayed in the gui?")

    ch_math_active = BoolProperty(default=False,
                              doc="should ch_math be displayed in the gui?")

    math_formula = StringProperty(default='ch1 * ch2',
                                  doc="formula for channel math")

    xy_mode = BoolProperty(default=False,
                           doc="in xy-mode, data are plotted vs the other "
                               "channel (instead of time)")

    _acquisition_started = BoolProperty(default=False,
                                        doc="whether a curve acquisition has been "
                                            "initiated")

    # DMA packet-layout versions this host can decode. The parser auto-detects the
    # version per packet (header [58:55]); both formats ship from the same RTL via
    # the DMA_PER_CHAN_TAG build option (3 = combined, 4 = per-channel tag).
    # v3/v4 = combined / per-channel-tag index-only; v5/v6 = the same with an
    # extra per-point value word (raw peak amplitudes -> reflectivity).
    # v7-v10 = the azimuth (Scanner360) variants of v3-v6: version = base +
    # 2*intensity + 4*azimuth; cell = {tick, mems}, data words carry a 4-bit
    # tick delta + the absolute MEMS step in the formerly-reserved span.
    _DMA_FMT_VERSIONS_SUPPORTED = (3, 4, 5, 6, 7, 8, 9, 10)

    def __init__(self, parent, name=None):
        super().__init__(parent, name=name)
        self._dma_udp_client = DmaUdpClient()
        self._last_dma_update = [-1, -1]

    @property
    def dma_stats(self):
        """Receiver-health snapshot from the DMA UDP client (packets/s, kernel
        drop count, per-channel update counters …). See DmaUdpClient.stats()."""
        return self._dma_udp_client.stats()

    @property
    def dma_max_parse_rate(self):
        """DMA frame-demand rate: packets/s the receiver must parse to refresh the
        whole point cloud at the desired fps. Normally driven from the display frame
        rate by Lidar (frame_rate x packets-per-frame); the receiver paces itself to
        a little above this (sleeping to yield the GIL) and the kernel sheds the
        board's over-send surplus. 0 parses every packet. A plain proxy to the client
        (computed value, not a persisted register)."""
        return self._dma_udp_client._max_parse_rate

    @dma_max_parse_rate.setter
    def dma_max_parse_rate(self, value):
        self._dma_udp_client.configure(max_parse_rate=value)

    @property
    def dma_zigzag_stride(self):
        """Scan row stride (the fast-axis cell count, pushed by the host):
        converts the whole-column dma_zigzag_shift into flat scan cells
        and derives each point's column. 0 disables the correction."""
        return self._dma_udp_client._zigzag_stride

    @dma_zigzag_stride.setter
    def dma_zigzag_stride(self, value):
        self._dma_udp_client.configure(zigzag_stride=value)

    @property
    def dma_zigzag_shift(self):
        """SLOW-axis zigzag correction (whole scan columns): the slow galvo
        axis lags its command, so with a bidirectional slow scan the
        descending-column raster lands offset from the ascending one by ~2x
        the lag (the swinging-block artifact in the live 2D view). The DMA
        parser shifts every point of a descending-column sweep by this many
        columns (x dma_zigzag_stride cells); ascending sweeps (= the
        unidirectional reference direction) define the frame and are left
        as-is. Applies live; plain proxy to the UDP client."""
        return self._dma_udp_client._zigzag_shift

    @dma_zigzag_shift.setter
    def dma_zigzag_shift(self, value):
        self._dma_udp_client.configure(zigzag_shift=value)

    @property
    def dma_intensity(self):
        """Runtime DMA intensity streaming: when True the FPGA appends a value
        word (raw peak amplitudes) to every point and stamps packet version
        v5/v6; the change lands at the next packet boundary. Setting it also
        switches the UDP client's decode mode so the reflectivity columns are
        (de)allocated to match. On bitstreams without the runtime register
        (capability bit 0x194[28] clear) writes are refused with a warning —
        the format there is fixed at build time."""
        return bool(self._dma_intensity_en) if self._dma_intensity_cap \
            else self.dma_fmt_version in (5, 6)

    @dma_intensity.setter
    def dma_intensity(self, value):
        value = bool(value)
        if not self._dma_intensity_cap:
            if value != (self.dma_fmt_version in (5, 6)):
                self._logger.warning(
                    "dma_intensity: bitstream has no runtime enable; the "
                    "packet format is fixed at version %d", self.dma_fmt_version)
            return
        self._dma_intensity_en = value
        # Keep the host decoder in step (buffer columns / value-word parsing).
        self._dma_udp_client.configure(intensity=value,
                                       dsz=self.fft_data_width)

    @property
    def dma_azimuth(self):
        """Scanner360 azimuth mode: the scan cell becomes {tick, mems} (motor
        tick x MEMS step instead of raster y*stride+x), the DMA frame becomes
        one motor TURN, and the packets stamp versions v7-v10 (data words carry
        a 4-bit tick delta + the absolute MEMS step). Setting it also switches
        the UDP client's decode (msw from the 0x1A4 descriptor). Refused on
        bitstreams without the capability bit 0x194[29]."""
        return bool(self._dma_azimuth_en) if self._dma_azimuth_cap \
            else self.dma_fmt_version in (7, 8, 9, 10)

    @dma_azimuth.setter
    def dma_azimuth(self, value):
        value = bool(value)
        if not self._dma_azimuth_cap:
            if value != (self.dma_fmt_version in (7, 8, 9, 10)):
                self._logger.warning(
                    "dma_azimuth: bitstream has no azimuth mode; the packet "
                    "format is fixed at version %d", self.dma_fmt_version)
            return
        self._dma_azimuth_en = value
        # Keep the host decoder in step (cell split tick/mems).
        self._dma_udp_client.configure(msw=self.dma_az_msw)

    @property
    def dma_refl_alpha(self):
        """Range exponent of the echo POWER loss used for the DMA reflectivity
        (intensity bitstreams v5/v6): rho ∝ A^2 * (bin-bin0)^alpha. 2 (default)
        = far-field diffuse target; tune empirically inside the beam focus.
        Applies live; plain proxy to the UDP client (not a persisted register)."""
        return self._dma_udp_client._refl_alpha

    @dma_refl_alpha.setter
    def dma_refl_alpha(self, value):
        self._dma_udp_client.configure(refl_alpha=value)

    @property
    def dma_refl_bin0(self):
        """Range-zero bin offset (fractional bins) of the DMA reflectivity:
        the beat bin of zero optical range (internal fiber/electrical delay).
        Points at/behind it get reflectivity 0. See dma_refl_alpha."""
        return self._dma_udp_client._refl_bin0

    @dma_refl_bin0.setter
    def dma_refl_bin0(self, value):
        self._dma_udp_client.configure(refl_bin0=value)

    @property
    def dma_refl_cal(self):
        """Optional per-integer-bin dB correction LUT for the DMA reflectivity
        (front-end response vs beat frequency, e.g. TIA rolloff). Assign an
        array indexed by FFT bin (measure with a flat target swept through
        range); assign [] to clear. See dma_refl_alpha."""
        return self._dma_udp_client._refl_cal

    @dma_refl_cal.setter
    def dma_refl_cal(self, value):
        self._dma_udp_client.configure(refl_cal=[] if value is None else value)

    @property
    def dma_refl_avg(self):
        """Reflectivity speckle-averaging count: bounded running mean over up
        to this many samples per scan cell (coherent returns fade several dB
        shot-to-shot; averaging narrows that ~sqrt(N)). 0 = no averaging.
        See dma_refl_avg_tol; applies live (proxy to the UDP client)."""
        return self._dma_udp_client._refl_avg

    @dma_refl_avg.setter
    def dma_refl_avg(self, value):
        self._dma_udp_client.configure(refl_avg=value)

    @property
    def dma_refl_avg_tol(self):
        """Max peak-index move (bins) for a new sample to join a cell's
        reflectivity average; a larger move means a different surface entered
        the cell, so the accumulation restarts. See dma_refl_avg."""
        return self._dma_udp_client._refl_avg_tol

    @dma_refl_avg_tol.setter
    def dma_refl_avg_tol(self, value):
        self._dma_udp_client.configure(refl_avg_tol=value)

    def _dma_configure_from_fpga(self):
        """Reconfigure the UDP unpacker from the FPGA packet-format descriptor.

        Reads the self-describing descriptor registers (0x170/0x194) so the host
        layout always matches the running bitstream. Called before the receive
        thread starts; warns (but proceeds) on a version it does not recognise.
        """
        version = self.dma_fmt_version
        if version not in self._DMA_FMT_VERSIONS_SUPPORTED:
            self._logger.warning(
                "DMA packet-format version %d not in supported %s; decoding may be "
                "wrong. Update pyrpl to match the FPGA bitstream.",
                version, self._DMA_FMT_VERSIONS_SUPPORTED)
        self._dma_udp_client.configure(
            fsz=self.dma_fmt_fsz,
            frac=self.dma_fmt_frac,
            hsz=self.dma_fmt_hsz,
            hist_block_size=self.dma_block_size,
            max_interval=self.dma_max_interval,
            seq_bits=self.dma_fmt_seq_bits,
            # v5/v6 (and the azimuth v9/v10) append a value word (raw peak
            # amplitudes, DSZ bits each, reg 0x34) per point; the client
            # derives reflectivity from it.
            dsz=self.fft_data_width,
            intensity=version in (5, 6, 9, 10),
            # Azimuth variants: cell = {tick, mems[msw-1:0]} (descriptor 0x1A4).
            msw=self.dma_az_msw if self._dma_azimuth_cap else None,
        )

    def _ownership_changed(self, old, new):
        """
        If the scope was in continuous mode when slaved, it has to stop!!
        """
        if new is not None:
            self.stop()
        # The DMA multicast receiver is tied to the acquisition *session*, not
        # the per-trace state machine: stop() is called once per trace (e.g. by
        # Lidar._start_trace_acquisition) to re-arm the scope, so tearing the
        # socket+thread down there churned it every frame. Tear it down only on
        # a genuine ownership change instead — scope freed at the end of a run,
        # or slaved away by another module.
        self._dma_udp_client.stop()

    @property
    def _fft_length(self):
        #  wp_last = self.fft_wp_last
        #  length1 = max(2, (wp_last & 0xffff) + 1)
        #  length2 = max(2, (wp_last >> 16) + 1)
        #  return min(length1, length2)
        return self.fft_length

    def get_fft_data(self, addr):
        """raw data from fft"""
        length = self._fft_length
        d = np.array(self._reads(addr, length), dtype=np.uint32)
        width = self.fft_data_width
        d[d >= 2 ** (width-1)] -= 2 ** width
        d = np.array(d, dtype=float) / 2**(width-1)
        d1 = d[np.arange(0, length, 2)]
        d2 = d[np.arange(1, length, 2)]
        return d2, d1

    def get_fft_history(self, addr, length, channel=None):
        """raw data from fft history.

        If channel (0=fft_a, 1=fft_b) is given, reads from the DMA UDP client
        instead of AXI-Lite registers and returns None when no new point data
        has arrived since the last call (liveness-driven, so it keeps updating
        even while the 2D scan is paused; see DmaUdpClient.max_interval).
        """
        if channel is not None:
            current = self._dma_udp_client.update_count(channel)
            if current == self._last_dma_update[channel]:
                return None
            self._last_dma_update[channel] = current
            frame = self._dma_udp_client.get_frame(channel, length)
            if frame is None:
                return None
            # Intensity bitstreams (v5/v6) append (refl_down, refl_up); this
            # legacy accessor returns only the peak indices.
            return frame[0], frame[1]
        d = np.array(self._reads(addr, length), dtype=np.uint32)
        d1 = np.array(d & 0xffff, dtype=np.int32)
        d2 = np.array(d >> 16, dtype=np.int32)
        return d2, d1

    @contextlib.contextmanager
    def fft_history_frame(self, channel, length, gate=True):
        """Zero-copy, recycled point-cloud frame from the DMA client (DMA only).

        Use as a context manager so the buffer is released back to the pool when
        done (no per-poll allocation at large frame sizes)::

            with scope.fft_history_frame(0, n) as f:
                if f is not None:
                    peak_down, peak_up = f    # READ-ONLY, valid only in the block

        gate=True (default) yields None when no new point data has arrived since
        the last gated call on this channel (liveness poll, mirrors
        get_fft_history); pass gate=False to always grab (e.g. a secondary
        channel already gated on the primary).
        """
        if gate:
            current = self._dma_udp_client.update_count(channel)
            if current == self._last_dma_update[channel]:
                yield None
                return
            self._last_dma_update[channel] = current
        with self._dma_udp_client.frame(channel, length) as f:
            yield f

    @property
    def _fftdata_ch1(self):
        return self.get_fft_data(0x30000)

    @property
    def _fftdata_ch2(self):
        return self.get_fft_data(0x40000)

    def _ffthist_ch1(self, length):
        return self.get_fft_history(0x50000, length, channel=0)

    def _ffthist_ch2(self, length):
        return self.get_fft_history(0x60000, length, channel=1)

    _fftdata = _fftdata_ch1
    _ffthist = _ffthist_ch1

    def _fftidx(self, length):
        d = np.array(self._reads(0x70000, length), dtype=np.uint32)
        return np.stack((d&0xffff, d>>16), axis=1)

    def _fftidx2(self, length):
        return np.array(self._reads(0xa0000, length), dtype=np.uint32)

    @property
    def _rawdata_ch1(self):
        """raw data from ch1"""
        # return np.array([self.to_pyint(v) for v in self._reads(0x10000,
        # self.data_length)],dtype=np.int32)
        x = np.array(self._reads(0x10000, self.data_length), dtype=np.int16)
        x[x >= 2 ** 13] -= 2 ** 14
        return x

    @property
    def _rawdata_ch2(self):
        """raw data from ch2"""
        # return np.array([self.to_pyint(v) for v in self._reads(0x20000,
        # self.data_length)],dtype=np.int32)

        x = np.array(self._reads(0x20000, self.data_length), dtype=np.int16)
        x[x >= 2 ** 13] -= 2 ** 14
        return x

    @property
    def _data_ch1(self):
        """ acquired (normalized) data from ch1"""
        return np.array(
            np.roll(self._rawdata_ch1, - (self._write_pointer_trigger +
                                          self._trigger_delay_register + 1)),
            dtype=float) / 2 ** 13

    @property
    def _data_ch2(self):
        """ acquired (normalized) data from ch2"""
        return np.array(
            np.roll(self._rawdata_ch2, - (self._write_pointer_trigger +
                                          self._trigger_delay_register + 1)),
            dtype=float) / 2 ** 13

        #  x = np.array(self._reads(0x60000, self.data_length//2), dtype=np.int16)
        #  y = np.array(self._reads(0x70000, self.data_length//2), dtype=np.int16)
        #  d = np.concatenate((x, y), axis=0)
        #  d[d >= 2 ** 13] -= 2 ** 14
        #  d = np.array(d, dtype=float) / 2 ** 13
        #  return d;

    @property
    def _data_ch1_current(self):
        """ (unnormalized) data from ch1 while acquisition is still running"""
        return np.array(
            np.roll(self._rawdata_ch1, -(self._write_pointer_current + 1)),
            dtype=float) / 2 ** 13

    @property
    def _data_ch2_current(self):
        """ (unnormalized) data from ch2 while acquisition is still running"""
        return np.array(
            np.roll(self._rawdata_ch2, -(self._write_pointer_current + 1)),
            dtype=float) / 2 ** 13

    @property
    def times(self):
        # duration = 8e-9*self.decimation*self.data_length
        # endtime = duration*
        duration = self.duration
        trigger_delay = self.trigger_delay
        if self.trigger_source!='immediately':
            return np.linspace(trigger_delay - duration / 2.,
                               trigger_delay + duration / 2.,
                               self.data_length, endpoint=False)
        else:
            return np.linspace(0,
                               duration,
                               self.data_length, endpoint=False)

    async def wait_for_pretrigger_async(self):
        """sleeps until scope trigger is ready (buffer has enough new data)"""
        while not self.pretrig_ok:
            await sleep_async(0.001)
        ### For some reason, launching the trigger at that point would be too soon...
        await sleep_async(0.1)

    def wait_for_pretrigger(self):
        """sleeps until scope trigger is ready (buffer has enough new data)"""
        wait(self.wait_for_pretrigger_async())

    def curve_ready(self):
        """
        Returns True if new data is ready for transfer
        """
        return (not self._trigger_armed) and \
               (not self._trigger_delay_running) and self._acquisition_started

    def _curve_acquiring(self):
        """
        Returns True if data is in the process of being acquired, i.e.
        waiting for trigger event or for acquisition of data after
        trigger event.
        """
        return (self._trigger_armed or self._trigger_delay_running) \
            and self._acquisition_started

    def _get_ch(self, ch):
        if ch not in [1, 2]:
            raise ValueError("channel should be 1 or 2, got " + str(ch))
        return self._data_ch1 if ch == 1 else self._data_ch2

    # Concrete implementation of AcquisitionModule methods
    # ----------------------------------------------------

    def _prepare_averaging(self):
        super(Scope, self)._prepare_averaging()
        self.data_x = np.copy(self.times)
        self.data_avg = np.zeros((2, len(self.times)))
        self.current_avg = 0


    def _get_trace(self):
        """
        Simply pack together channel 1 and channel 2 curves in a numpy array
        """
        return np.array((self._get_ch(1), self._get_ch(2)))

    def _remaining_time(self):
        """
        :returns curve duration - ellapsed duration since last setup() call.
        """
        return self.duration - (time() - self._last_time_setup)

    async def _do_average_continuous_async(self):
        if not self._is_rolling_mode_active():
            await super(Scope, self)._do_average_continuous_async()
        else: # no need to prepare averaging
            self._start_acquisition_rolling_mode()
            while(self.running_state=="running_continuous"):
                await sleep_async(self.MIN_DELAY_CONTINUOUS_ROLLING_MS*0.001)
                self.data_x, self.data_avg = self._get_rolling_curve()
                self._emit_signal_by_name('display_curve', [self.data_x, self.data_avg])

    def _data_ready(self):
        """
        :return: True if curve is ready in the hardware, False otherwise.
        """
        return self.curve_ready()

    def _start_trace_acquisition(self):
        """
        Start acquisition of a curve in rolling_mode=False
        """
        if self.fft_enable and self.dma_nch and not self._dma_udp_client._running:
            self._dma_udp_client._unicast = self.dma_unicast
            # Board IP for the unicast NAT hole-punch registration. Prefer the
            # live peer address of the register link (already resolved); fall
            # back to the configured hostname.
            board_ip = None
            try:
                board_ip = self._client.socket.getpeername()[0]
            except (OSError, AttributeError):
                board_ip = getattr(self._client, '_hostname', None)
            self._dma_udp_client._board_ip = board_ip
            self._dma_configure_from_fpga()
            self._dma_udp_client.start()
        autosave_backup = self._autosave_active
        self._autosave_active = False  # Don't save anything in config file
        # during setup!! # maybe even better in
        # BaseModule ??
        self._acquisition_started = True

        # 0. reset state machine
        self._reset_writestate_machine = True

        # set the trigger delay:
        # 1. in mode "immediately", trace goes from 0 to duration,
        if self.trigger_source == 'immediately':
            self._trigger_delay_register = self.data_length
        else: #  2. triggering on real signal
            #  a. convert float delay into counts
            delay = int(np.round(self.trigger_delay / self.sampling_time)) + \
                    self.data_length // 2
            #  b. Do the proper roundings of the trigger delay
            if delay <= 0:
                delay = 1  # bug in scope code: 0 does not work
            elif delay > 2 ** 32 - 1:
                delay = 2 ** 32 - 1
            # c. set the trigger_delay in the right fpga register
            self._trigger_delay_register = delay

        # 4. Arm the trigger: curve acquisition will only start passed this
        self._trigger_armed = True
        # 5. In case immediately, setting again _trigger_source_register
        # will cause a "software_trigger"
        self._trigger_source_register = self.trigger_source

        self._autosave_active = autosave_backup
        self._last_time_setup = time()

    def _start_acquisition_rolling_mode(self):
        self._start_trace_acquisition()
        self._trigger_source_register = 'off'
        self._trigger_armed = True

    # Rolling_mode related methods:
    # -----------------------------

    #def _start_acquisition_rolling_mode(self):
    #    self._start_acquisition()
    #    self._trigger_source_register = 'off'
    #   self._trigger_armed = True

    def _rolling_mode_allowed(self):
        """
        Only if duration larger than 0.1 s
        """
        return self.duration > 0.1

    def _is_rolling_mode_active(self):
        """
        Rolling_mode property evaluates to True and duration larger than 0.1 s
        """
        return self.rolling_mode and self._rolling_mode_allowed()

    def _get_ch_no_roll(self, ch):
        if ch not in [1, 2]:
            raise ValueError("channel should be 1 or 2, got " + str(ch))
        return self._rawdata_ch1 * 1. / 2 ** 13 if ch == 1 else \
            self._rawdata_ch2 * 1. / 2 ** 13

    def _get_rolling_curve(self):
        datas = np.zeros((2, len(self.times)))
        # Rolling mode
        wp0 = self._write_pointer_current  # write pointer
        # before acquisition
        times = self.times
        times -= times[-1]

        for ch, active in (
                (0, self.ch1_active),
                (1, self.ch2_active)):
            if active:
                datas[ch] = self._get_ch_no_roll(ch + 1)
        wp1 = self._write_pointer_current  # write pointer after
        #  acquisition
        for index, active in [(0, self.ch1_active),
                              (1, self.ch2_active)]:
            if active:
                data = datas[index]
                to_discard = (wp1 - wp0) % self.data_length  # remove
                #  data that have been affected during acq.
                data = np.roll(data, self.data_length - wp0)[
                       to_discard:]
                data = np.concatenate([[np.nan] * to_discard, data])
                datas[index] = data
        return times, datas

    # Custom behavior of AcquisitionModule methods for scope:
    # -------------------------------------------------------

    def save_curve(self):
        """
        Saves the curve(s) that is (are) currently displayed in the gui in
        the db_system. Also, returns the list [curve_ch1, curve_ch2]...
        """
        d = self.attributes_last_run
        curves = [None, None]
        for ch, active in [(0, self.ch1_active),
                           (1, self.ch2_active)]:
            if active:
                d.update({'ch': ch,
                          'name': self.curve_name + ' ch' + str(ch + 1)})
                curves[ch] = self._save_curve(self.data_x,
                                              self.data_avg[ch],
                                              **d)
        return curves
