// fft_ip_ssr — SSR FFT using LogiCORE sub-FFTs, Decimation-In-Frequency (DIF) architecture.
// AXI-Stream I/O, magnitude output, bit-reversed bin order.
//
// DIF vs Decimation-In-Time (DIT) decomposition for SSR=2:
//   DIF (this module): the first butterfly stage splits the N-point problem by
//     output bin parity — sub-FFT 0 computes even-indexed bins X[0,2,4,...],
//     sub-FFT 1 computes odd-indexed bins X[1,3,5,...].
//   DIT (Vitis xf::dsp::fft, FFT_IMPL==2): the first stage splits by input
//     sample index — sub-FFT 0 gets even-indexed samples, sub-FFT 1 gets odd.
//     This groups output bins by lower/upper spectrum half instead of even/odd.
//
// Output ordering (drives the BRAM channel/address split in fft_proc.sv):
//   SSR=1: single LogiCORE in bit_reversed_order → beat b = X[bit_rev(b, NFFT)]
//   SSR=2: both sub-FFTs run in bit_reversed_order →
//           beat b = {X[2·bit_rev(b,SUB_NFFT)], X[2·bit_rev(b,SUB_NFFT)+1]}
//   SSR=4: four sub-FFTs in bit_reversed_order →
//           beat b = {X[4·bit_rev(b,SUB_NFFT)], X[4·bit_rev(b,SUB_NFFT)+1],
//                     X[4·bit_rev(b,SUB_NFFT)+2], X[4·bit_rev(b,SUB_NFFT)+3]}
//   DIF lanes hold bins by residue mod FSSR: channel = k[SSR_BITS-1:0].
//   FFT_IMPL==2 (DIT) uses channel = k[MSB] instead. See fft_proc.sv.
//
// Compile flags: -DFFT_SSR=<1|2|4|8> -DFFT_NFFT=<log2(N)>

#include <hls_stream.h>
#include <ap_axi_sdata.h>
#include <ap_fixed.h>
#include <ap_int.h>
#include <complex>
#include <hls_fft.h>
#include <hls_math.h>
// Precomputed twiddle ROM (W_N^k), generated by gen_twiddle_lut for the build's
// FFT_SIZE/FFT_SSR/TWID_W. Replaces on-the-fly CORDIC twiddle (get_twiddle) to cut
// logic/congestion on the route-bound pll_ser_clk paths. Only the SSR>=2 DIF
// pre-stages use twiddles, so SSR=1 needs no ROM (the generator only emits SSR 2/4).
#if FFT_SSR >= 2
#include "fft_ip_ssr_twiddle.hpp"
#endif

// ============================================================
// Compile-time configuration
// ============================================================

#if FFT_SSR == 1
  #define SSR_LOG2 0
#elif FFT_SSR == 2
  #define SSR_LOG2 1
#elif FFT_SSR == 4
  #define SSR_LOG2 2
#elif FFT_SSR == 8
  #define SSR_LOG2 3
#else
  #error "FFT_SSR must be 1, 2, 4, or 8"
#endif

#define FFT_SIZE (1 << FFT_NFFT)
#define SUB_NFFT (FFT_NFFT - SSR_LOG2)   // log2(N/SSR)
#define SUB_SIZE (1 << SUB_NFFT)          // N/SSR samples per serial sub-FFT

#ifndef ASZ
#define ASZ 14   // ADC word width (hardware-fixed)
#endif
#ifndef DSZ
#define DSZ 28   // output magnitude width
#endif

// AXI-Stream packing:
//   input:  FSSR ADC samples, each ASZ bits, byte-rounded total
//   output: FSSR magnitudes, each DSZ bits
#define IN_WIDTH  (((ASZ * FFT_SSR + 7) / 8) * 8)
#define OUT_WIDTH (DSZ * FFT_SSR)

typedef ap_axiu<IN_WIDTH,  0, 0, 0> axis_in_t;
typedef ap_axiu<OUT_WIDTH, 0, 0, 0> axis_out_t;

// ============================================================
// Fixed-point types
// ============================================================

// INTERNAL_W: internal FFT datapath width (the fixed-point precision carried through
// the butterflies/twiddles), NOT an integer-bit count. Wider = lower quantization
// floor = more small-signal dynamic range, at a cost of FFT-core DSP/BRAM. Override
// with -DINTERNAL_W (build knob FFT_INTERNAL_W). Default 16.
// MUST be a multiple of 8: hls::fft byte-rounds the I/O datapath to ceil(W/8)*8 and
// the cfixed_t array type must match it, so 16/24/32 are the only usable values — a
// non-multiple (e.g. 20) fails to compile (no matching hls::fft overload) and would
// round up to the next byte anyway (no BRAM saving vs the rounded width).
#ifndef INTERNAL_W
#define INTERNAL_W 16
#endif
static_assert(INTERNAL_W % 8 == 0,
    "INTERNAL_W (FFT_INTERNAL_W) must be a multiple of 8 (hls::fft byte-rounds the datapath; use 16/24/32).");
// CORDIC vectoring-mode magnitude iterations (used unless USE_APPROXIMATION is set).
// Build knob FFT_CORDIC_ITER (default 10): fewer iterations = smaller pipeline (less
// FF/LUT) at lower magnitude accuracy (~iter bits). 10 is ample for peak detection;
// 16 = full precision but ~1.6x the CORDIC area. Below ~5 the approx is better.
#ifndef CORDIC_ITER
#define CORDIC_ITER 10
#endif
static const int TWID_W = 18;  // twiddle factor precision

typedef std::complex<ap_fixed<INTERNAL_W, 1>>   cfixed_t;
typedef std::complex<ap_fixed<TWID_W, 2>> cfixed_twid_t;
typedef ap_fixed<INTERNAL_W + TWID_W + 1, 4>   fixed_mul_t;  // scalar multiply accumulator

// Sub-FFT output sample type. hls::fft byte-rounds the datapath and fixes the xn/xk
// element types: input = ap_fixed<byteround(input_width),1>, output =
// ap_fixed<byteround(output_width), byteround(output_width)-input_width+1> (see the
// 1-channel fixed-point overload in hls_fft.h). cfixed_out_t MUST match that exactly.
//   scaled:   output_width = INTERNAL_W           -> OUT_W = INTERNAL_W, OUT_I = 1
//             (identical to cfixed_t; existing scaled datapath unchanged).
//   unscaled: output_width = byteround(INTERNAL_W + SUB_NFFT + 1) (the hls::fft golden
//             value; grows over the N/SSR sub-transform); OUT_I integer, INTERNAL_W-1 frac.
#ifdef FFT_UNSCALED
static const int OUT_W = (((INTERNAL_W + SUB_NFFT + 1) + 7) / 8) * 8;
#else
static const int OUT_W = (((INTERNAL_W) + 7) / 8) * 8;
#endif
static const int OUT_I = OUT_W - INTERNAL_W + 1;
typedef ap_fixed<OUT_W, OUT_I>     fixed_out_t;
typedef std::complex<fixed_out_t>  cfixed_out_t;

// ============================================================
// LogiCORE FFT configuration
// ============================================================

// Avnet per-stage scaling schedule: alternating "10"/"01" + "11" final
// Prevents overflow while maximising precision for a given sub-FFT depth.
static constexpr int scale_sched(int n) {
    int ibits = (n + 1) / 2;
    int bits  = (n % 2 == 0) ? 2 : 1;               // "10" or "01"
    for (int i = 1; i < ibits - 1; i++) bits = (bits << 2) | 2; // append "10"
    bits = (bits << 2) | 3;                           // append "11"
    return bits;
}

// Fixed-length build: a single compile-time schedule for the max NFFT.
static const int SCALE_SCHED = scale_sched(SUB_NFFT);

#ifdef FFT_RUNTIME_NFFT
// Per-size scaling schedule table, indexed by the runtime sub-FFT exponent.
// With run-time configurable length the schedule must match the configured NFFT
// (a smaller transform uses fewer butterfly stages), so we cannot bake in a
// single SCALE_SCHED — we look it up by sub_nfft at frame start. Filled at
// compile time (constexpr) into a ROM; scale_sched(n) is unchanged.
struct sched_lut_t {
    int v[SUB_NFFT + 1];
    constexpr sched_lut_t() : v() {
        for (int n = 0; n <= SUB_NFFT; n++) v[n] = scale_sched(n);
    }
};
static const sched_lut_t SCALE_SCHED_LUT;
#endif

// ---- Build-knob helpers: collapse to compile-time constants when fixed-length.
// RT_N(rt, konst):    loop trip count / size      — runtime value vs constant
// RT_NFFT(rt, konst): an nfft-like exponent        — runtime value vs constant
// RT_TW(i, sh):       twiddle ROM index            — strided vs direct
// When FFT_RUNTIME_NFFT is unset every site folds to the original constant so the
// generated RTL (and LUT/timing) is identical to the fixed-length design; the
// runtime args passed in are then dead and optimised away.
#ifdef FFT_RUNTIME_NFFT
  #define RT_N(rt, konst)    (rt)
  #define RT_NFFT(rt, konst) (rt)
  #define RT_TW(i, sh)       ((i) << (sh))
#else
  #define RT_N(rt, konst)    (konst)
  #define RT_NFFT(rt, konst) (konst)
  #define RT_TW(i, sh)       (i)
#endif

struct fft_params_t : hls::ip_fft::params_t {
#ifdef FFT_NATURAL_ORDER
    // natural_order: the LogiCORE sub-FFTs add an internal reorder buffer so bins
    // stream out in spectral order. Required when the peak detector interpolates
    // (peak_frac != 0) — sub-bin interp reads adjacent bins, only adjacent in natural
    // order. output_ssr2/4 then emit beat b = {X[FSSR·b .. FSSR·b+FSSR-1]} (natural),
    // and fft_proc.sv uses non-bit-reversed readback addressing to match. Costs one
    // reorder buffer per sub-FFT (extra BRAM) vs bit_reversed_order.
    static const unsigned ordering_opt       = hls::ip_fft::natural_order;
#else
    // bit_reversed_order costs no internal reorder buffer in LogiCORE.
    // The output permutation is handled by BRAM addressing in fft_proc.sv.
    static const unsigned ordering_opt       = hls::ip_fft::bit_reversed_order;
#endif
    static const unsigned max_nfft           = SUB_NFFT;
    static const unsigned input_width        = INTERNAL_W;
#ifdef FFT_UNSCALED
    // Unscaled: no per-stage /2; hls::fft requires output_width =
    // byteround(input_width + max_nfft + 1) == OUT_W (see hls_fft.h golden check).
    static const unsigned scaling_opt        = hls::ip_fft::unscaled;
    static const unsigned output_width       = OUT_W;
#else
    static const unsigned scaling_opt        = hls::ip_fft::scaled;
    static const unsigned output_width       = INTERNAL_W;
#endif
    static const unsigned status_width       = 8;
#ifdef FFT_RUNTIME_NFFT
    // Run-time configurable transform length (build knob FFT_RUNTIME_NFFT): the
    // generated LogiCORE accepts an NFFT field in the config word, so one
    // synthesized core (built for max_nfft = SUB_NFFT) can run any 2^n sub-FFT
    // with n <= SUB_NFFT. The surrounding dataflow loops are bounded by the
    // runtime size below. Mirrors IMPL==1's run_time_configurable_transform_length
    // xfft. Costs ~2700 LUTs vs the fixed-length build, so it is opt-in.
    static const bool     has_nfft           = true;
    // config word = NFFT field (low 8 bits, padded) + per-stage scaling schedule
    // (2 bits/stage, scaled only) + 1 direction bit, byte-rounded. The +8 is the
    // NFFT field. Unscaled has no scaling schedule, so those 2*ceil/2 bits drop out
    // (else checkConfig errors: the wrapper only counts schedule bits when scaled).
  #ifdef FFT_UNSCALED
    static const unsigned config_width       = ((1+8+7)/8)*8;
  #else
    static const unsigned config_width       = ((2*((SUB_NFFT+1)/2)+1+8+7)/8)*8;
  #endif
#else
    // Fixed-length: NFFT baked in at max_nfft, no config NFFT field.
  #ifdef FFT_UNSCALED
    static const unsigned config_width       = ((1+7)/8)*8;
  #else
    static const unsigned config_width       = ((2*((SUB_NFFT+1)/2)+1+7)/8)*8;
  #endif
#endif
    static const unsigned phase_factor_width = TWID_W;
    static const unsigned stages_block_ram   = (SUB_NFFT < 10) ? 0 : SUB_NFFT - 9;
#ifdef FFT_MULT_LUT
    // DSP->LUT trade: implement the twiddle complex multipliers and butterflies
    // in CLB/LUT logic instead of XtremeDSP. Frees DSP48 (relieves the ~98% DSP
    // wall at SSR=4) at the cost of more LUTs and lower per-mult Fmax. Default
    // (unset) keeps DSP-based mults: complex_mult_type=use_mults_resources,
    // butterfly_type=use_xtremedsp.
    static const unsigned complex_mult_type = hls::ip_fft::use_luts;
    static const unsigned butterfly_type    = hls::ip_fft::use_luts;
#endif
};

typedef hls::ip_fft::config_t<fft_params_t> fft_config_t;
typedef hls::ip_fft::status_t<fft_params_t> fft_status_t;

// ============================================================
// SSR >= 2: parallel-sample pair struct
// ============================================================

#if FFT_SSR >= 2
struct par_data {
    cfixed_t data0;
    cfixed_t data1;
};

static cfixed_t cmul(cfixed_t d, cfixed_twid_t w) {
#pragma HLS INLINE
    fixed_mul_t re = d.real()*w.real() - d.imag()*w.imag();
    fixed_mul_t im = d.real()*w.imag() + d.imag()*w.real();
    cfixed_t r;
    r.real(re);
    r.imag(im);
    return r;
}
#endif

#if FFT_SSR == 4
struct par_data4 {
    cfixed_t data[4];
};
#endif

#if FFT_SSR == 8
struct par_data8 {
    cfixed_t data[8];
};
#endif

// ============================================================
// Shared helpers
// ============================================================

// DIF twiddle factor W_N^k = exp(-j 2π k/N), read from the precomputed ROM
// (twid_re_1/twid_im_1 = cos(2πk/N)/-sin(2πk/N), index k in [0, N/SSR) here).
// ROM lookup instead of on-the-fly CORDIC: far less logic, relaxing the
// route-bound pll_ser_clk paths. twid_lut_t matches cfixed_twid_t (ap_fixed<18,2>).
#if FFT_SSR >= 2
static inline cfixed_twid_t get_twiddle(int k) {
#pragma HLS INLINE
    cfixed_twid_t w;
    w.real(twid_re_1[k]);
    w.imag(twid_im_1[k]);
    return w;
}
#endif

#if FFT_SSR == 4
// Row-2 twiddle W_N^{2k} for the SSR=4 stage-2 butterflies. The ROM stores
// W_N^{2k} as twid_re_2/twid_im_2[k] (k in [0, N/4)), so this is a direct lookup
// rather than indexing twid_re_1 at 2*i (which is out of range for SSR=4).
static inline cfixed_twid_t get_twiddle2(int k) {
#pragma HLS INLINE
    cfixed_twid_t w;
    w.real(twid_re_2[k]);
    w.imag(twid_im_2[k]);
    return w;
}
#endif

#if FFT_SSR == 8
// Per-row twiddle accessors for the SSR=8 output stage. Row r stores W_N^{r*k}
// (twid_re_r/twid_im_r[k], k in [0, N/8)); sub-FFT lane r multiplies A_r by it.
static inline cfixed_twid_t get_twiddle_row(int row, int k) {
#pragma HLS INLINE
    cfixed_twid_t w;
    switch (row) {
        case 1: w.real(twid_re_1[k]); w.imag(twid_im_1[k]); break;
        case 2: w.real(twid_re_2[k]); w.imag(twid_im_2[k]); break;
        case 3: w.real(twid_re_3[k]); w.imag(twid_im_3[k]); break;
        case 4: w.real(twid_re_4[k]); w.imag(twid_im_4[k]); break;
        case 5: w.real(twid_re_5[k]); w.imag(twid_im_5[k]); break;
        case 6: w.real(twid_re_6[k]); w.imag(twid_im_6[k]); break;
        default:w.real(twid_re_7[k]); w.imag(twid_im_7[k]); break;
    }
    return w;
}

// Multiply by W_8^2 = -j: (a + jb) -> (b - ja). Pure wiring, no multiplier.
static inline cfixed_t mul_neg_j(cfixed_t d) {
#pragma HLS INLINE
    cfixed_t r;
    r.real( d.imag());
    r.imag(-d.real());
    return r;
}

// Constant 8th-root twiddles for the radix-8 sub-DFT butterfly network.
// W_8^1 = (√2/2)(1 - j),  W_8^3 = (√2/2)(-1 - j).  W_8^0/2 are handled as
// pass-through / mul_neg_j, so only these two need a real complex multiply.
static const double SQRT1_2 = 0.70710678118654752;
static inline cfixed_twid_t w8_1() {
#pragma HLS INLINE
    cfixed_twid_t w; w.real( SQRT1_2); w.imag(-SQRT1_2); return w;
}
static inline cfixed_twid_t w8_3() {
#pragma HLS INLINE
    cfixed_twid_t w; w.real(-SQRT1_2); w.imag(-SQRT1_2); return w;
}
#endif

// CORDIC vectoring-mode magnitude (default; ported from fft_ssr_native.cpp). Selected
// unless USE_APPROXIMATION is defined, in which case the alpha-max-beta-min
// approximation below is used. Operates on the sub-FFT output component fixed_out_t
// (widened in unscaled mode). cord_t carries +2 integer bits of CORDIC growth headroom
// and +14 fractional bits for <0.02% gain precision.
#ifndef USE_APPROXIMATION
// +2 integer bits of CORDIC growth headroom, +8 fractional bits below the input LSB
// for iteration/gain precision (ample for CORDIC_ITER<=~12; keeps the magnitude's
// INTERNAL_W-1 fractional accuracy). Narrower than IMPL=4's +14 to save pipeline FF.
typedef ap_fixed<OUT_W + 8, OUT_I + 2> cord_t;
static cord_t cordic_magnitude_raw(fixed_out_t re_in, fixed_out_t im_in) {
#pragma HLS INLINE
    cord_t x = (re_in < 0) ? cord_t(-re_in) : cord_t(re_in);
    cord_t y = (im_in < 0) ? cord_t(-im_in) : cord_t(im_in);
    const cord_t cordic_gain = 0.607252935;
    for (int i = 0; i < CORDIC_ITER; i++) {
#pragma HLS PIPELINE II=1
        cord_t xs = x >> i;
        cord_t ys = y >> i;
        if (y > 0) { x = x + ys; y = y - xs; }
        else       { x = x - ys; y = y + xs; }
    }
    return x * cordic_gain;
}
#endif

// Magnitude of a sub-FFT output sample -> DSZ-bit unsigned.
//   scaled  : input in [-1,1), |z| in [0,~1.5) -> DSZ-bit fixed with 2 integer bits
//             (unchanged from the original scaled build).
//   unscaled: |z| spans [0,~1.5*2^SUB_NFFT); narrow to DSZ by keeping the low bits
//             (LSB = 2^-(INTERNAL_W-1)) and saturating the top — the FFT_SCALED=2
//             "saturating" convention, matching IMPL=4's magnitude() guard.
static inline ap_uint<DSZ> magnitude(cfixed_out_t v) {
#pragma HLS INLINE
#ifdef USE_APPROXIMATION
    // Alpha-max-beta-min: |z| ≈ max(|re|,|im|) + 3/8·min(|re|,|im|)
    typedef ap_fixed<OUT_W + 1, OUT_I + 1> wider_t;
    wider_t re = v.real() < 0 ? (wider_t)(-v.real()) : (wider_t)v.real();
    wider_t im = v.imag() < 0 ? (wider_t)(-v.imag()) : (wider_t)v.imag();
    wider_t mx = (re > im) ? re : im;
    wider_t mn = (re > im) ? im : re;
    // Register the min-approximation add (latency=1) to split the CARRY4 chain
    // (compare -> add -> add -> cast) that otherwise binds pll_ser_clk.
    wider_t mn_approx = (mn >> 2) + (mn >> 3);
#pragma HLS BIND_OP variable=mn_approx op=add latency=1
    wider_t mag = mx + mn_approx;
#else
    cord_t mag = cordic_magnitude_raw(v.real(), v.imag());
#endif

#ifdef FFT_UNSCALED
    // Saturating narrow: reinterpret |z|'s bit pattern as an unsigned integer
    // (value scaled by 2^(INTERNAL_W-1), i.e. OUT_W-OUT_I = INTERNAL_W-1 frac bits),
    // keep the low DSZ bits, saturate above. == IMPL=4 magnitude() guard.
    const int MAGBITS = OUT_W + 2;
    ap_ufixed<MAGBITS, OUT_I + 2> umag = mag;
    ap_uint<MAGBITS> bits = umag.range(MAGBITS - 1, 0);
    return (bits >> DSZ) ? ap_uint<DSZ>(-1) : ap_uint<DSZ>(bits);
#else
    ap_ufixed<DSZ, 2> out = mag;
    return out.range(DSZ-1, 0);
#endif
}

// Convert a raw signed ASZ-bit ADC sample to the internal ap_fixed<INTERNAL_W,1> value
// in [-1,1) by MSB-aligning it into the top ASZ bits. A plain value cast
// (ap_fixed<INTERNAL_W,1>(raw)) WRAPS any |raw|>=1 — i.e. it zeroes the whole 14-bit
// ADC input — which silently broke the FFT (csim: every tone collapsed to bin 0).
// Matches fft_ip_ssr.cpp's input handling.
static inline ap_fixed<INTERNAL_W,1> adc_to_fixed(ap_int<ASZ> raw) {
#pragma HLS INLINE
    ap_fixed<INTERNAL_W,1> v = 0;
    v.range(INTERNAL_W-1, INTERNAL_W-ASZ) = raw;
    return v;
}

// hls::fft (2020.1) takes C arrays, not streams, so each FFT needs an array feed
// and drain. These run as processes in the TOP-level DATAFLOW region alongside
// hls::fft — matching the canonical Xilinx FFT example's two-level dataflow
// (fft_top → hls::fft). Wrapping them in an intermediate fft_serial() function
// adds a third dataflow level that corrupts hls::fft's internal xn_cp/xk_cp
// buffers (they degrade to ROM/BRAM and the stream-based FFT wrapper is wired to
// memory ports), so the feed/fft/drain are inlined into the top function below.
// sub_size = 2^sub_nfft is the runtime sub-FFT length (<= SUB_SIZE). The config
// word is programmed here: direction, the runtime NFFT, and the matching scaling
// schedule. The LogiCORE then transforms exactly the first sub_size elements.
static void fft_feed(hls::stream<cfixed_t> &in,
                     cfixed_t xn[SUB_SIZE],
                     fft_config_t *cfg,
                     int sub_size,
                     unsigned sub_nfft) {
    cfg->setDir(1);
#ifdef FFT_RUNTIME_NFFT
    cfg->setNfft(sub_nfft);
  #ifndef FFT_UNSCALED
    // Unscaled has no per-stage schedule; setSch()->checkSch() errors unless scaled.
    cfg->setSch(SCALE_SCHED_LUT.v[sub_nfft]);
  #endif
#else
    (void)sub_nfft;
  #ifndef FFT_UNSCALED
    cfg->setSch(SCALE_SCHED);
  #endif
#endif
    for (int i = 0; i < RT_N(sub_size, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        xn[i] = in.read();
    }
}

static void fft_drain(cfixed_out_t xk[SUB_SIZE],
                      hls::stream<cfixed_out_t> &out,
                      fft_status_t *sts,
                      int sub_size) {
    (void)*sts;  // overflow status unused
    for (int i = 0; i < RT_N(sub_size, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        out.write(xk[i]);
    }
}

// ============================================================
// SSR = 1  (single serial FFT, no butterfly stage)
// ============================================================
#if FFT_SSR == 1

static void input_ssr1(hls::stream<axis_in_t> &s_axis,
                       hls::stream<cfixed_t>  &out,
                       int n) {
    for (int i = 0; i < RT_N(n, FFT_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=FFT_SIZE
        ap_int<ASZ> raw = s_axis.read().data.range(ASZ-1, 0);
        cfixed_t v;
        v.real(adc_to_fixed(raw));
        v.imag(0);
        out.write(v);
    }
}

static void output_ssr1(hls::stream<cfixed_t>   &in,
                        hls::stream<axis_out_t> &m_axis,
                        int n) {
    for (int i = 0; i < RT_N(n, FFT_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=FFT_SIZE
        axis_out_t pkt;
        pkt.data.range(DSZ-1, 0) = magnitude(in.read());
        pkt.last = (i == RT_N(n, FFT_SIZE) - 1);
        m_axis.write(pkt);
    }
}

#endif // FFT_SSR == 1

// ============================================================
// SSR = 2  (DIF: stage-1 butterfly + two serial sub-FFTs)
// ============================================================
#if FFT_SSR == 2

// Unpack two ASZ-bit ADC samples per beat → par_data stream
static void input_ssr2(hls::stream<axis_in_t> &s_axis,
                       hls::stream<par_data>  &out,
                       int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        auto d = s_axis.read().data;
        par_data t;
        t.data0.real(adc_to_fixed((ap_int<ASZ>)d.range(  ASZ-1,     0)));
        t.data0.imag(0);
        t.data1.real(adc_to_fixed((ap_int<ASZ>)d.range(2*ASZ-1,   ASZ)));
        t.data1.imag(0);
        out.write(t);
    }
}

// Reorder interleaved {x[2k],x[2k+1]} → split {x[k], x[k+N/2]}
// Buffers one full frame (2×SUB_SIZE samples) before outputting.
static void reorder(hls::stream<par_data> &din,
                    hls::stream<par_data> &dout,
                    int n) {
    int half = RT_N(n, SUB_SIZE) >> 1;
    cfixed_t buff[2][SUB_SIZE];
#pragma HLS ARRAY_PARTITION variable=buff complete dim=1
#pragma HLS ARRAY_PARTITION variable=buff cyclic factor=2 dim=2

    // First N/2 samples → buff[0]
    for (int k = 0; k < half; k++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=4 max=SUB_SIZE/2
        par_data t = din.read();
        buff[0][2*k]   = t.data0;
        buff[0][2*k+1] = t.data1;
    }
    // Second N/2 samples → buff[1]
    for (int k = 0; k < half; k++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=4 max=SUB_SIZE/2
        par_data t = din.read();
        buff[1][2*k]   = t.data0;
        buff[1][2*k+1] = t.data1;
    }
    // Output beat k = { x[k], x[k+N/2] }
    for (int k = 0; k < RT_N(n, SUB_SIZE); k++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data t;
        t.data0 = buff[0][k];
        t.data1 = buff[1][k];
        dout.write(t);
    }
}

// Stage-1 DIF butterfly: y0=(x0+x1)/2, y1=(x0-x1)/2
static void radix2p(hls::stream<par_data> &din,
                    hls::stream<par_data> &dout,
                    int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data t = din.read();
        typedef ap_fixed<INTERNAL_W+1, 2> wide_t;
        wide_t a = t.data0.real() + t.data1.real();
        wide_t b = t.data0.imag() + t.data1.imag();
        wide_t c = t.data0.real() - t.data1.real();
        wide_t d = t.data0.imag() - t.data1.imag();
        par_data r;
        r.data0.real(a>>1); r.data0.imag(b>>1);
        r.data1.real(c>>1); r.data1.imag(d>>1);
        dout.write(r);
    }
}

// Twiddle: multiply data1 by W_N^k; pass data0 unchanged
// tw_shift = SUB_NFFT - sub_nfft: the twiddle ROM stores W_{maxN}^k; at a runtime
// length N' = maxN >> tw_shift the needed factor is W_{N'}^i = W_{maxN}^{i<<tw_shift}.
static void twiddle(hls::stream<par_data> &din,
                    hls::stream<cfixed_t> &dout0,
                    hls::stream<cfixed_t> &dout1,
                    int n,
                    int tw_shift) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data t = din.read();
        dout0.write(t.data0);
        dout1.write(cmul(t.data1, get_twiddle(RT_TW(i, tw_shift))));
    }
}

// Joiner + magnitude: stream sub-FFT outputs → m_axis
// With bit_reversed_order sub-FFTs:
//   beat b = { |X[2·bit_rev(b,SUB_NFFT)]|, |X[2·bit_rev(b,SUB_NFFT)+1]| }
static void output_ssr2(hls::stream<cfixed_out_t> &fft0_out,
                        hls::stream<cfixed_out_t> &fft1_out,
                        hls::stream<axis_out_t>   &m_axis,
                        int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        axis_out_t pkt;
        pkt.data.range(  DSZ-1,   0) = magnitude(fft0_out.read());
        pkt.data.range(2*DSZ-1, DSZ) = magnitude(fft1_out.read());
        pkt.last = (i == RT_N(n, SUB_SIZE) - 1);
        m_axis.write(pkt);
    }
}

#endif // FFT_SSR == 2

// ============================================================
// SSR = 4  (DIF: two radix-2 stages + four serial sub-FFTs)
// ============================================================
#if FFT_SSR == 4

// Unpack four ASZ-bit ADC samples per beat → par_data4 stream
static void input_ssr4(hls::stream<axis_in_t>  &s_axis,
                       hls::stream<par_data4>  &out,
                       int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        auto d = s_axis.read().data;
        par_data4 t;
        for (int q = 0; q < 4; q++) {
#pragma HLS UNROLL
            t.data[q].real(adc_to_fixed((ap_int<ASZ>)d.range((q+1)*ASZ-1, q*ASZ)));
            t.data[q].imag(0);
        }
        out.write(t);
    }
}

// Reorder interleaved {x[4k]..x[4k+3]} → split {x[k], x[k+N/4], x[k+N/2], x[k+3N/4]}
// Input arrives as SUB_SIZE beats of 4 consecutive samples each.
// Reorganised as SUB_SIZE beats where beat k has the four samples needed for the
// radix-4 DIF butterfly: one from each N/4-sample quarter of the frame.
//
// Storage is explicitly banked as buff[quarter][bank][depth] with both leading
// dims fully partitioned. This avoids the cyclic-partition modulo addressing
// (which put a divide on the write critical path) — each of the 16 sub-arrays is
// indexed only by the depth counter on writes.
// sub_nfft = log2(runtime sub-FFT length); the quarter/depth split scales with it.
// buff is sized for the max length and only the low [0,DEPTH) depths are used.
static void reorder_ssr4(hls::stream<par_data4> &din,
                         hls::stream<par_data4> &dout,
                         int n,
                         int sub_nfft) {
    static const int MAX_DEPTH = SUB_SIZE / 4;
    int DEPTH = RT_N(n, SUB_SIZE) >> 2;
    cfixed_t buff[4][4][MAX_DEPTH];
#pragma HLS ARRAY_PARTITION variable=buff complete dim=1
#pragma HLS ARRAY_PARTITION variable=buff complete dim=2

    // Write: beat i belongs to quarter q (DEPTH beats per quarter); its four
    // samples land in the four banks at the same depth d. DEPTH is a power of
    // two, so q and d are bit-slices of i (top 2 bits / low bits) — pure wiring,
    // no induction add/select on the address path.
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data4 t = din.read();
        ap_uint<2> q = i >> (RT_NFFT(sub_nfft, SUB_NFFT) - 2);
        int        d = i & (DEPTH - 1);
        for (int b = 0; b < 4; b++) {
#pragma HLS UNROLL
            buff[q][b][d] = t.data[b];
        }
    }
    // Output beat k = {x[k], x[k+N/4], x[k+N/2], x[k+3N/4]}.
    // Position k within a quarter sits at bank k%4, depth k/4 (both power-of-two
    // slices of k — cheap). The bank select is a small 4:1 mux per quarter.
    for (int k = 0; k < RT_N(n, SUB_SIZE); k++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        ap_uint<2>          bank  = k & 0x3;
        int                 depth = k >> 2;
        par_data4 t;
        for (int qq = 0; qq < 4; qq++) {
#pragma HLS UNROLL
            t.data[qq] = buff[qq][bank][depth];
        }
        dout.write(t);
    }
}

// Stage-1 DIF butterfly on pairs (lane0,lane2) and (lane1,lane3).
// Twiddle for lane2: W_N^k.  Twiddle for lane3: W_N^{k+N/4} = W_N^k * (-j).
// Outputs split into two par_data streams: upper={out0,out1}, lower={out2,out3}.
static void stage1_ssr4(hls::stream<par_data4> &din,
                        hls::stream<par_data>  &upper,
                        hls::stream<par_data>  &lower,
                        int n,
                        int tw_shift) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data4 t = din.read();
        typedef ap_fixed<INTERNAL_W+1, 2> wide_t;

        wide_t a0r = t.data[0].real() + t.data[2].real();
        wide_t a0i = t.data[0].imag() + t.data[2].imag();
        wide_t a1r = t.data[1].real() + t.data[3].real();
        wide_t a1i = t.data[1].imag() + t.data[3].imag();
        wide_t q0r = t.data[0].real() - t.data[2].real();
        wide_t q0i = t.data[0].imag() - t.data[2].imag();
        wide_t q1r = t.data[1].real() - t.data[3].real();
        wide_t q1i = t.data[1].imag() - t.data[3].imag();

        cfixed_t out0, out1, q0, q1;
        out0.real(a0r >> 1); out0.imag(a0i >> 1);
        out1.real(a1r >> 1); out1.imag(a1i >> 1);
        q0.real(q0r >> 1);   q0.imag(q0i >> 1);
        q1.real(q1r >> 1);   q1.imag(q1i >> 1);

        cfixed_twid_t w = get_twiddle(RT_TW(i, tw_shift));
        cfixed_t out2   = cmul(q0, w);
        // W_N^{k+N/4} = W_N^k * (-j): multiply by (-j) rotates (a+jb) → (b-ja)
        cfixed_t q1w    = cmul(q1, w);
        cfixed_t out3;
        out3.real( q1w.imag());
        out3.imag(-q1w.real());

        par_data pu, pl;
        pu.data0 = out0; pu.data1 = out1;
        pl.data0 = out2; pl.data1 = out3;
        upper.write(pu);
        lower.write(pl);
    }
}

// Stage-2 DIF butterfly on the upper half {out0, out1}.
// out0 → sub-FFT for bins ≡ 0 mod 4; out1 → bins ≡ 2 mod 4.
// Twiddle: W_{N/2}^k = W_N^{2k}.
static void stage2_upper(hls::stream<par_data>  &din,
                         hls::stream<cfixed_t>  &fft0_in,
                         hls::stream<cfixed_t>  &fft2_in,
                         int n,
                         int tw_shift) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data t = din.read();
        typedef ap_fixed<INTERNAL_W+1, 2> wide_t;
        wide_t f0r = t.data0.real() + t.data1.real();
        wide_t f0i = t.data0.imag() + t.data1.imag();
        wide_t  dr = t.data0.real() - t.data1.real();
        wide_t  di = t.data0.imag() - t.data1.imag();
        cfixed_t f0, d;
        f0.real(f0r >> 1); f0.imag(f0i >> 1);
        d.real(dr >> 1);   d.imag(di >> 1);
        fft0_in.write(f0);
        fft2_in.write(cmul(d, get_twiddle2(RT_TW(i, tw_shift))));
    }
}

// Stage-2 DIF butterfly on the lower half {out2, out3}.
// out2 → sub-FFT for bins ≡ 1 mod 4; out3 → bins ≡ 3 mod 4.
// Twiddle: W_{N/2}^k = W_N^{2k}.
static void stage2_lower(hls::stream<par_data>  &din,
                         hls::stream<cfixed_t>  &fft1_in,
                         hls::stream<cfixed_t>  &fft3_in,
                         int n,
                         int tw_shift) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data t = din.read();
        typedef ap_fixed<INTERNAL_W+1, 2> wide_t;
        wide_t f1r = t.data0.real() + t.data1.real();
        wide_t f1i = t.data0.imag() + t.data1.imag();
        wide_t  dr = t.data0.real() - t.data1.real();
        wide_t  di = t.data0.imag() - t.data1.imag();
        cfixed_t f1, d;
        f1.real(f1r >> 1); f1.imag(f1i >> 1);
        d.real(dr >> 1);   d.imag(di >> 1);
        fft1_in.write(f1);
        fft3_in.write(cmul(d, get_twiddle2(RT_TW(i, tw_shift))));
    }
}

// Joiner + magnitude: four sub-FFT outputs → m_axis.
// With bit_reversed_order sub-FFTs:
//   beat b = {|X[4·bit_rev(b,SUB_NFFT)]|, |X[4·bit_rev(b,SUB_NFFT)+1]|,
//              |X[4·bit_rev(b,SUB_NFFT)+2]|, |X[4·bit_rev(b,SUB_NFFT)+3]|}
static void output_ssr4(hls::stream<cfixed_out_t> &fft0_out,
                        hls::stream<cfixed_out_t> &fft1_out,
                        hls::stream<cfixed_out_t> &fft2_out,
                        hls::stream<cfixed_out_t> &fft3_out,
                        hls::stream<axis_out_t>   &m_axis,
                        int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        axis_out_t pkt;
        pkt.data.range(  DSZ-1,     0) = magnitude(fft0_out.read());
        pkt.data.range(2*DSZ-1,   DSZ) = magnitude(fft1_out.read());
        pkt.data.range(3*DSZ-1, 2*DSZ) = magnitude(fft2_out.read());
        pkt.data.range(4*DSZ-1, 3*DSZ) = magnitude(fft3_out.read());
        pkt.last = (i == RT_N(n, SUB_SIZE) - 1);
        m_axis.write(pkt);
    }
}

#endif // FFT_SSR == 4

// ============================================================
// SSR = 8  (DIF: three radix-2 stages + eight serial sub-FFTs)
// ============================================================
// Per beat k the network gathers the eight samples {x[k+q·N/8]}_{q=0..7} and
// computes their 8-point DFT A_r = Σ_q x[k+q·N/8]·W_8^{qr}, then forms the
// sub-FFT input g_r = A_r·W_N^{kr}.  Sub-FFT r (length N/8) then produces the
// output bins ≡ r mod 8.  The 8-point DFT is a radix-2 DIF flowgraph (3 stages,
// each scaled >>1 → total /8), so only the constant W_8^{1,3} rotations need a
// real multiply; W_8^{0,2}=1,-j are pass-through / swap.  The beat-dependent
// W_N^{kr} multiplies (ROM rows 1..7) are folded into the final stage.
#if FFT_SSR == 8

// Scaled radix-2 butterfly: sum=(a+b)/2, dif=(a-b)/2.  Done in wide_t so the
// pre-shift a±b can reach [-2,2) without overflow, then >>1 back into [-1,1).
static inline void bfly8(cfixed_t a, cfixed_t b, cfixed_t &sum, cfixed_t &dif) {
#pragma HLS INLINE
    typedef ap_fixed<INTERNAL_W+1, 2> wide_t;
    wide_t sr = a.real() + b.real();
    wide_t si = a.imag() + b.imag();
    wide_t dr = a.real() - b.real();
    wide_t di = a.imag() - b.imag();
    sum.real(sr >> 1); sum.imag(si >> 1);
    dif.real(dr >> 1); dif.imag(di >> 1);
}

// Unpack eight ASZ-bit ADC samples per beat → par_data8 stream
static void input_ssr8(hls::stream<axis_in_t>  &s_axis,
                       hls::stream<par_data8>  &out,
                       int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        auto d = s_axis.read().data;
        par_data8 t;
        for (int q = 0; q < 8; q++) {
#pragma HLS UNROLL
            t.data[q].real(adc_to_fixed((ap_int<ASZ>)d.range((q+1)*ASZ-1, q*ASZ)));
            t.data[q].imag(0);
        }
        out.write(t);
    }
}

// Reorder {x[8k]..x[8k+7]} → {x[k], x[k+N/8], ..., x[k+7N/8]} (eight-way analog
// of reorder_ssr4).  buff[eighth][bank][depth] with the two leading dims fully
// partitioned, so writes index only by depth and reads by a depth + 8:1 bank mux.
static void reorder_ssr8(hls::stream<par_data8> &din,
                         hls::stream<par_data8> &dout,
                         int n,
                         int sub_nfft) {
    static const int MAX_DEPTH = SUB_SIZE / 8;
    int DEPTH = RT_N(n, SUB_SIZE) >> 3;
    cfixed_t buff[8][8][MAX_DEPTH];
#pragma HLS ARRAY_PARTITION variable=buff complete dim=1
#pragma HLS ARRAY_PARTITION variable=buff complete dim=2

    // Write: beat i → eighth q (top 3 bits of i), depth d (low bits); its eight
    // samples land in the eight banks at the same depth.
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data8 t = din.read();
        ap_uint<3> q = i >> (RT_NFFT(sub_nfft, SUB_NFFT) - 3);
        int        d = i & (DEPTH - 1);
        for (int b = 0; b < 8; b++) {
#pragma HLS UNROLL
            buff[q][b][d] = t.data[b];
        }
    }
    // Output beat k = {x[k+q·N/8]}: position k sits at bank k%8, depth k/8.
    for (int k = 0; k < RT_N(n, SUB_SIZE); k++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        ap_uint<3> bank  = k & 0x7;
        int        depth = k >> 3;
        par_data8 t;
        for (int qq = 0; qq < 8; qq++) {
#pragma HLS UNROLL
            t.data[qq] = buff[qq][bank][depth];
        }
        dout.write(t);
    }
}

// 8-point DFT stage 1: radix-2 butterfly on (q, q+4), q=0..3, with the constant
// W_8^q rotation applied to the difference lane.
static void dft8_stage1(hls::stream<par_data8> &din,
                        hls::stream<par_data8> &dout,
                        int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data8 t = din.read();
        par_data8 s;
        cfixed_t sum, dif;
        bfly8(t.data[0], t.data[4], sum, dif); s.data[0] = sum; s.data[4] = dif;                 // W_8^0 = 1
        bfly8(t.data[1], t.data[5], sum, dif); s.data[1] = sum; s.data[5] = cmul(dif, w8_1());    // W_8^1
        bfly8(t.data[2], t.data[6], sum, dif); s.data[2] = sum; s.data[6] = mul_neg_j(dif);       // W_8^2 = -j
        bfly8(t.data[3], t.data[7], sum, dif); s.data[3] = sum; s.data[7] = cmul(dif, w8_3());    // W_8^3
        dout.write(s);
    }
}

// 8-point DFT stage 2: radix-2 butterfly on (q, q+2) within each half {0..3},
// {4..7}, with the constant W_4^i rotation (i=0→1, i=1→-j) on the difference.
static void dft8_stage2(hls::stream<par_data8> &din,
                        hls::stream<par_data8> &dout,
                        int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data8 t = din.read();
        par_data8 s;
        cfixed_t sum, dif;
        for (int base = 0; base < 8; base += 4) {
#pragma HLS UNROLL
            bfly8(t.data[base+0], t.data[base+2], sum, dif); s.data[base+0] = sum; s.data[base+2] = dif;             // W_4^0 = 1
            bfly8(t.data[base+1], t.data[base+3], sum, dif); s.data[base+1] = sum; s.data[base+3] = mul_neg_j(dif);  // W_4^1 = -j
        }
        dout.write(s);
    }
}

// 8-point DFT stage 3 + output twiddle: radix-2 butterfly on (q, q+1), then the
// DIF bit-reversal A[r]=s3[bitrev3(r)], then g_r = A_r·W_N^{kr} (ROM rows 1..7,
// lane 0 has no twiddle).  Each g_r feeds its serial sub-FFT.
static void dft8_stage3_twiddle(hls::stream<par_data8> &din,
                                hls::stream<cfixed_t>  &fft0_in,
                                hls::stream<cfixed_t>  &fft1_in,
                                hls::stream<cfixed_t>  &fft2_in,
                                hls::stream<cfixed_t>  &fft3_in,
                                hls::stream<cfixed_t>  &fft4_in,
                                hls::stream<cfixed_t>  &fft5_in,
                                hls::stream<cfixed_t>  &fft6_in,
                                hls::stream<cfixed_t>  &fft7_in,
                                int n,
                                int tw_shift) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        par_data8 t = din.read();
        cfixed_t s3[8];
        cfixed_t sum, dif;
        for (int base = 0; base < 8; base += 2) {
#pragma HLS UNROLL
            bfly8(t.data[base], t.data[base+1], sum, dif);
            s3[base] = sum; s3[base+1] = dif;
        }
        // DIF natural-order outputs: A[r] = s3[bitrev3(r)].
        cfixed_t a0 = s3[0], a1 = s3[4], a2 = s3[2], a3 = s3[6];
        cfixed_t a4 = s3[1], a5 = s3[5], a6 = s3[3], a7 = s3[7];
        int tw = RT_TW(i, tw_shift);
        fft0_in.write(a0);                                     // lane 0: W_N^0 = 1
        fft1_in.write(cmul(a1, get_twiddle_row(1, tw)));
        fft2_in.write(cmul(a2, get_twiddle_row(2, tw)));
        fft3_in.write(cmul(a3, get_twiddle_row(3, tw)));
        fft4_in.write(cmul(a4, get_twiddle_row(4, tw)));
        fft5_in.write(cmul(a5, get_twiddle_row(5, tw)));
        fft6_in.write(cmul(a6, get_twiddle_row(6, tw)));
        fft7_in.write(cmul(a7, get_twiddle_row(7, tw)));
    }
}

// Joiner + magnitude: eight sub-FFT outputs → m_axis.
//   beat b = {|X[8·bit_rev(b,SUB_NFFT)+lane]|} for lane = 0..7
static void output_ssr8(hls::stream<cfixed_out_t> &fft0_out,
                        hls::stream<cfixed_out_t> &fft1_out,
                        hls::stream<cfixed_out_t> &fft2_out,
                        hls::stream<cfixed_out_t> &fft3_out,
                        hls::stream<cfixed_out_t> &fft4_out,
                        hls::stream<cfixed_out_t> &fft5_out,
                        hls::stream<cfixed_out_t> &fft6_out,
                        hls::stream<cfixed_out_t> &fft7_out,
                        hls::stream<axis_out_t>   &m_axis,
                        int n) {
    for (int i = 0; i < RT_N(n, SUB_SIZE); i++) {
#pragma HLS PIPELINE II=1
#pragma HLS LOOP_TRIPCOUNT min=8 max=SUB_SIZE
        axis_out_t pkt;
        pkt.data.range(  DSZ-1,     0) = magnitude(fft0_out.read());
        pkt.data.range(2*DSZ-1,   DSZ) = magnitude(fft1_out.read());
        pkt.data.range(3*DSZ-1, 2*DSZ) = magnitude(fft2_out.read());
        pkt.data.range(4*DSZ-1, 3*DSZ) = magnitude(fft3_out.read());
        pkt.data.range(5*DSZ-1, 4*DSZ) = magnitude(fft4_out.read());
        pkt.data.range(6*DSZ-1, 5*DSZ) = magnitude(fft5_out.read());
        pkt.data.range(7*DSZ-1, 6*DSZ) = magnitude(fft6_out.read());
        pkt.data.range(8*DSZ-1, 7*DSZ) = magnitude(fft7_out.read());
        pkt.last = (i == RT_N(n, SUB_SIZE) - 1);
        m_axis.write(pkt);
    }
}

#endif // FFT_SSR == 8

// ============================================================
// Top-level function
// ============================================================

void fft_hls_direct(hls::stream<axis_in_t>  &s_axis,
                hls::stream<axis_out_t> &m_axis,
                bool                    &event_frame_started
#ifdef FFT_RUNTIME_NFFT
                , ap_uint<5>            nfft
#endif
                )
{
#pragma HLS INTERFACE axis port=s_axis
#pragma HLS INTERFACE axis port=m_axis
// ap_vld (not ap_none): the value written here is constant true, so ap_none would
// expose only that constant-1 data wire (event_frame_started stuck high -> fft_proc
// counts every cycle). ap_vld additionally exposes event_frame_started_ap_vld, a
// clean 1-cycle pulse at each function (frame) entry — that is what the BD wires to
// the event_frame_started port for per-frame counting.
#pragma HLS INTERFACE ap_vld port=event_frame_started
#ifdef FFT_RUNTIME_NFFT
// nfft = per-lane sub-FFT exponent (log2 of the runtime sub-FFT length), driven
// from fft_proc.sv's fft_nfft. Held stable for the whole frame (the design only
// reconfigures once after reset), so ap_stable: no handshake, treated as constant
// within a transaction.
#pragma HLS INTERFACE ap_stable port=nfft
#endif
#pragma HLS INTERFACE ap_ctrl_none port=return

    event_frame_started = true;

    // Runtime sizing shared by every dataflow process. sub_size = 2^sub_nfft is the
    // per-lane serial FFT length; tw_shift strides the twiddle ROM (built for the
    // max length SUB_NFFT) down to the runtime length. With the knob off these are
    // the compile-time max constants and the RT_* macros fold every use back to a
    // constant, so the RTL matches the fixed-length design exactly.
#ifdef FFT_RUNTIME_NFFT
    // Clamp to SUB_NFFT so an out-of-range request can never index past the ROM.
    unsigned sub_nfft = nfft;
    if (sub_nfft > (unsigned)SUB_NFFT) sub_nfft = SUB_NFFT;
    int sub_size = 1 << sub_nfft;
    int tw_shift = SUB_NFFT - sub_nfft;
#else
    unsigned sub_nfft = SUB_NFFT;
    int sub_size = SUB_SIZE;
    int tw_shift = 0;
#endif
    (void)sub_nfft; (void)sub_size; (void)tw_shift;

#pragma HLS DATAFLOW

#if FFT_SSR == 1

    hls::stream<cfixed_t> pre_fft("pre_fft");
    hls::stream<cfixed_t> post_fft("post_fft");
#pragma HLS STREAM variable=pre_fft  depth=16
#pragma HLS STREAM variable=post_fft depth=16
    cfixed_t     xn[SUB_SIZE];
    cfixed_t     xk[SUB_SIZE];
    fft_config_t cfg;
    fft_status_t sts;

    input_ssr1 (s_axis, pre_fft, sub_size);
    fft_feed   (pre_fft, xn, &cfg, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn, xk, &sts, &cfg);
    fft_drain  (xk, post_fft, &sts, sub_size);
    output_ssr1(post_fft, m_axis, sub_size);

#elif FFT_SSR == 2

    hls::stream<par_data>  raw_par    ("raw_par");
    hls::stream<par_data>  reorder_out("reorder_out");
    hls::stream<par_data>  radix_out  ("radix_out");
    hls::stream<cfixed_t>  tw_out0    ("tw_out0");
    hls::stream<cfixed_t>  tw_out1    ("tw_out1");
    hls::stream<cfixed_out_t> fft0_out ("fft0_out");
    hls::stream<cfixed_out_t> fft1_out ("fft1_out");
#pragma HLS STREAM variable=raw_par      depth=16
#pragma HLS STREAM variable=reorder_out  depth=16
#pragma HLS STREAM variable=radix_out    depth=16
#pragma HLS STREAM variable=tw_out0      depth=16
#pragma HLS STREAM variable=tw_out1      depth=16
#pragma HLS STREAM variable=fft0_out     depth=16
#pragma HLS STREAM variable=fft1_out     depth=16
    cfixed_t     xn0[SUB_SIZE], xn1[SUB_SIZE];
    cfixed_out_t xk0[SUB_SIZE], xk1[SUB_SIZE];
    fft_config_t cfg0, cfg1;
    fft_status_t sts0, sts1;

    input_ssr2 (s_axis, raw_par, sub_size);
    reorder    (raw_par, reorder_out, sub_size);
    radix2p    (reorder_out, radix_out, sub_size);
    twiddle    (radix_out, tw_out0, tw_out1, sub_size, tw_shift);
    fft_feed   (tw_out0, xn0, &cfg0, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn0, xk0, &sts0, &cfg0);
    fft_drain  (xk0, fft0_out, &sts0, sub_size);
    fft_feed   (tw_out1, xn1, &cfg1, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn1, xk1, &sts1, &cfg1);
    fft_drain  (xk1, fft1_out, &sts1, sub_size);
    output_ssr2(fft0_out, fft1_out, m_axis, sub_size);

#elif FFT_SSR == 4

    hls::stream<par_data4>  raw_par4    ("raw_par4");
    hls::stream<par_data4>  reorder_out ("reorder_out");
    hls::stream<par_data>   upper       ("upper");
    hls::stream<par_data>   lower       ("lower");
    hls::stream<cfixed_t>   fft0_in     ("fft0_in");
    hls::stream<cfixed_t>   fft1_in     ("fft1_in");
    hls::stream<cfixed_t>   fft2_in     ("fft2_in");
    hls::stream<cfixed_t>   fft3_in     ("fft3_in");
    hls::stream<cfixed_out_t> fft0_out  ("fft0_out");
    hls::stream<cfixed_out_t> fft1_out  ("fft1_out");
    hls::stream<cfixed_out_t> fft2_out  ("fft2_out");
    hls::stream<cfixed_out_t> fft3_out  ("fft3_out");
#pragma HLS STREAM variable=raw_par4    depth=16
#pragma HLS STREAM variable=reorder_out depth=16
#pragma HLS STREAM variable=upper       depth=16
#pragma HLS STREAM variable=lower       depth=16
#pragma HLS STREAM variable=fft0_in     depth=16
#pragma HLS STREAM variable=fft1_in     depth=16
#pragma HLS STREAM variable=fft2_in     depth=16
#pragma HLS STREAM variable=fft3_in     depth=16
#pragma HLS STREAM variable=fft0_out    depth=16
#pragma HLS STREAM variable=fft1_out    depth=16
#pragma HLS STREAM variable=fft2_out    depth=16
#pragma HLS STREAM variable=fft3_out    depth=16
    cfixed_t     xn0[SUB_SIZE], xn1[SUB_SIZE], xn2[SUB_SIZE], xn3[SUB_SIZE];
    cfixed_out_t xk0[SUB_SIZE], xk1[SUB_SIZE], xk2[SUB_SIZE], xk3[SUB_SIZE];
    fft_config_t cfg0, cfg1, cfg2, cfg3;
    fft_status_t sts0, sts1, sts2, sts3;

    input_ssr4  (s_axis, raw_par4, sub_size);
    reorder_ssr4(raw_par4, reorder_out, sub_size, sub_nfft);
    stage1_ssr4 (reorder_out, upper, lower, sub_size, tw_shift);
    stage2_upper(upper, fft0_in, fft2_in, sub_size, tw_shift);
    stage2_lower(lower, fft1_in, fft3_in, sub_size, tw_shift);
    fft_feed (fft0_in, xn0, &cfg0, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn0, xk0, &sts0, &cfg0);
    fft_drain(xk0, fft0_out, &sts0, sub_size);
    fft_feed (fft1_in, xn1, &cfg1, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn1, xk1, &sts1, &cfg1);
    fft_drain(xk1, fft1_out, &sts1, sub_size);
    fft_feed (fft2_in, xn2, &cfg2, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn2, xk2, &sts2, &cfg2);
    fft_drain(xk2, fft2_out, &sts2, sub_size);
    fft_feed (fft3_in, xn3, &cfg3, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn3, xk3, &sts3, &cfg3);
    fft_drain(xk3, fft3_out, &sts3, sub_size);
    output_ssr4 (fft0_out, fft1_out, fft2_out, fft3_out, m_axis, sub_size);

#elif FFT_SSR == 8

    hls::stream<par_data8>  raw_par8    ("raw_par8");
    hls::stream<par_data8>  reorder_out ("reorder_out");
    hls::stream<par_data8>  s1_out      ("s1_out");
    hls::stream<par_data8>  s2_out      ("s2_out");
    hls::stream<cfixed_t>     fft_in[8];
    hls::stream<cfixed_out_t> fft_out[8];
#pragma HLS STREAM variable=raw_par8    depth=16
#pragma HLS STREAM variable=reorder_out depth=16
#pragma HLS STREAM variable=s1_out      depth=16
#pragma HLS STREAM variable=s2_out      depth=16
#pragma HLS STREAM variable=fft_in      depth=16
#pragma HLS STREAM variable=fft_out     depth=16
#pragma HLS ARRAY_PARTITION variable=fft_in  complete dim=1
#pragma HLS ARRAY_PARTITION variable=fft_out complete dim=1
    cfixed_t     xn0[SUB_SIZE], xn1[SUB_SIZE], xn2[SUB_SIZE], xn3[SUB_SIZE];
    cfixed_t     xn4[SUB_SIZE], xn5[SUB_SIZE], xn6[SUB_SIZE], xn7[SUB_SIZE];
    cfixed_out_t xk0[SUB_SIZE], xk1[SUB_SIZE], xk2[SUB_SIZE], xk3[SUB_SIZE];
    cfixed_out_t xk4[SUB_SIZE], xk5[SUB_SIZE], xk6[SUB_SIZE], xk7[SUB_SIZE];
    fft_config_t cfg0, cfg1, cfg2, cfg3, cfg4, cfg5, cfg6, cfg7;
    fft_status_t sts0, sts1, sts2, sts3, sts4, sts5, sts6, sts7;

    input_ssr8  (s_axis, raw_par8, sub_size);
    reorder_ssr8(raw_par8, reorder_out, sub_size, sub_nfft);
    dft8_stage1 (reorder_out, s1_out, sub_size);
    dft8_stage2 (s1_out, s2_out, sub_size);
    dft8_stage3_twiddle(s2_out,
                        fft_in[0], fft_in[1], fft_in[2], fft_in[3],
                        fft_in[4], fft_in[5], fft_in[6], fft_in[7],
                        sub_size, tw_shift);
    fft_feed (fft_in[0], xn0, &cfg0, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn0, xk0, &sts0, &cfg0);
    fft_drain(xk0, fft_out[0], &sts0, sub_size);
    fft_feed (fft_in[1], xn1, &cfg1, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn1, xk1, &sts1, &cfg1);
    fft_drain(xk1, fft_out[1], &sts1, sub_size);
    fft_feed (fft_in[2], xn2, &cfg2, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn2, xk2, &sts2, &cfg2);
    fft_drain(xk2, fft_out[2], &sts2, sub_size);
    fft_feed (fft_in[3], xn3, &cfg3, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn3, xk3, &sts3, &cfg3);
    fft_drain(xk3, fft_out[3], &sts3, sub_size);
    fft_feed (fft_in[4], xn4, &cfg4, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn4, xk4, &sts4, &cfg4);
    fft_drain(xk4, fft_out[4], &sts4, sub_size);
    fft_feed (fft_in[5], xn5, &cfg5, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn5, xk5, &sts5, &cfg5);
    fft_drain(xk5, fft_out[5], &sts5, sub_size);
    fft_feed (fft_in[6], xn6, &cfg6, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn6, xk6, &sts6, &cfg6);
    fft_drain(xk6, fft_out[6], &sts6, sub_size);
    fft_feed (fft_in[7], xn7, &cfg7, sub_size, sub_nfft);
    hls::fft<fft_params_t>(xn7, xk7, &sts7, &cfg7);
    fft_drain(xk7, fft_out[7], &sts7, sub_size);
    output_ssr8 (fft_out[0], fft_out[1], fft_out[2], fft_out[3],
                 fft_out[4], fft_out[5], fft_out[6], fft_out[7], m_axis, sub_size);

#endif
}
